# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.srcs/sources_1/bd/design_2/ip/design_2_axi_noc_0_0/design_2_axi_noc_0_0.xci
# IP: The module: 'design_2_axi_noc_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axi_noc_0_0/bd_0/bd_48e0.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_48e0 || ORIG_REF_NAME==bd_48e0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axi_noc_0_0/bd_0/ip/ip_0/bd_48e0_HBM03_AXI_nmu_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_48e0_HBM03_AXI_nmu_0 || ORIG_REF_NAME==bd_48e0_HBM03_AXI_nmu_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axi_noc_0_0/bd_0/ip/ip_1/bd_48e0_const_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_48e0_const_0_0 || ORIG_REF_NAME==bd_48e0_const_0_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axi_noc_0_0/bd_0/ip/ip_2/bd_48e0_HBM02_AXI_nmu_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_48e0_HBM02_AXI_nmu_0 || ORIG_REF_NAME==bd_48e0_HBM02_AXI_nmu_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axi_noc_0_0/bd_0/ip/ip_3/bd_48e0_HBM01_AXI_nmu_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_48e0_HBM01_AXI_nmu_0 || ORIG_REF_NAME==bd_48e0_HBM01_AXI_nmu_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axi_noc_0_0/bd_0/ip/ip_4/bd_48e0_HBM00_AXI_nmu_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_48e0_HBM00_AXI_nmu_0 || ORIG_REF_NAME==bd_48e0_HBM00_AXI_nmu_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axi_noc_0_0/bd_0/ip/ip_5/bd_48e0_MC_hbmc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_48e0_MC_hbmc_0 || ORIG_REF_NAME==bd_48e0_MC_hbmc_0} -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axi_noc_0_0/bd_0/ip/ip_0/xdc/bd_48e0_HBM03_AXI_nmu_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_48e0_HBM03_AXI_nmu_0 || ORIG_REF_NAME==bd_48e0_HBM03_AXI_nmu_0} -quiet] {/bd_48e0_HBM03_AXI_nmu_0_top_INST } ]/bd_48e0_HBM03_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axi_noc_0_0/bd_0/ip/ip_2/xdc/bd_48e0_HBM02_AXI_nmu_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_48e0_HBM02_AXI_nmu_0 || ORIG_REF_NAME==bd_48e0_HBM02_AXI_nmu_0} -quiet] {/bd_48e0_HBM02_AXI_nmu_0_top_INST } ]/bd_48e0_HBM02_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axi_noc_0_0/bd_0/ip/ip_3/xdc/bd_48e0_HBM01_AXI_nmu_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_48e0_HBM01_AXI_nmu_0 || ORIG_REF_NAME==bd_48e0_HBM01_AXI_nmu_0} -quiet] {/bd_48e0_HBM01_AXI_nmu_0_top_INST } ]/bd_48e0_HBM01_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axi_noc_0_0/bd_0/ip/ip_4/xdc/bd_48e0_HBM00_AXI_nmu_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_48e0_HBM00_AXI_nmu_0 || ORIG_REF_NAME==bd_48e0_HBM00_AXI_nmu_0} -quiet] {/bd_48e0_HBM00_AXI_nmu_0_top_INST } ]/bd_48e0_HBM00_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axi_noc_0_0/bd_0/ip/ip_5/hdl/par/bd_48e0_MC_hbmc_0_ip.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_48e0_MC_hbmc_0 || ORIG_REF_NAME==bd_48e0_MC_hbmc_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axi_noc_0_0/design_2_axi_noc_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_axi_noc_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axi_noc_0_0/design_2_axi_noc_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_axi_noc_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axi_noc_0_0/design_2_axi_noc_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_axi_noc_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.srcs/sources_1/bd/design_2/ip/design_2_axi_noc_0_0/design_2_axi_noc_0_0.xci
# IP: The module: 'design_2_axi_noc_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axi_noc_0_0/bd_0/bd_48e0.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_48e0 || ORIG_REF_NAME==bd_48e0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axi_noc_0_0/bd_0/ip/ip_0/bd_48e0_HBM03_AXI_nmu_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_48e0_HBM03_AXI_nmu_0 || ORIG_REF_NAME==bd_48e0_HBM03_AXI_nmu_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axi_noc_0_0/bd_0/ip/ip_1/bd_48e0_const_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_48e0_const_0_0 || ORIG_REF_NAME==bd_48e0_const_0_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axi_noc_0_0/bd_0/ip/ip_2/bd_48e0_HBM02_AXI_nmu_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_48e0_HBM02_AXI_nmu_0 || ORIG_REF_NAME==bd_48e0_HBM02_AXI_nmu_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axi_noc_0_0/bd_0/ip/ip_3/bd_48e0_HBM01_AXI_nmu_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_48e0_HBM01_AXI_nmu_0 || ORIG_REF_NAME==bd_48e0_HBM01_AXI_nmu_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axi_noc_0_0/bd_0/ip/ip_4/bd_48e0_HBM00_AXI_nmu_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_48e0_HBM00_AXI_nmu_0 || ORIG_REF_NAME==bd_48e0_HBM00_AXI_nmu_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axi_noc_0_0/bd_0/ip/ip_5/bd_48e0_MC_hbmc_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_48e0_MC_hbmc_0 || ORIG_REF_NAME==bd_48e0_MC_hbmc_0} -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axi_noc_0_0/bd_0/ip/ip_0/xdc/bd_48e0_HBM03_AXI_nmu_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_48e0_HBM03_AXI_nmu_0 || ORIG_REF_NAME==bd_48e0_HBM03_AXI_nmu_0} -quiet] {/bd_48e0_HBM03_AXI_nmu_0_top_INST } ]/bd_48e0_HBM03_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axi_noc_0_0/bd_0/ip/ip_2/xdc/bd_48e0_HBM02_AXI_nmu_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_48e0_HBM02_AXI_nmu_0 || ORIG_REF_NAME==bd_48e0_HBM02_AXI_nmu_0} -quiet] {/bd_48e0_HBM02_AXI_nmu_0_top_INST } ]/bd_48e0_HBM02_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axi_noc_0_0/bd_0/ip/ip_3/xdc/bd_48e0_HBM01_AXI_nmu_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_48e0_HBM01_AXI_nmu_0 || ORIG_REF_NAME==bd_48e0_HBM01_AXI_nmu_0} -quiet] {/bd_48e0_HBM01_AXI_nmu_0_top_INST } ]/bd_48e0_HBM01_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axi_noc_0_0/bd_0/ip/ip_4/xdc/bd_48e0_HBM00_AXI_nmu_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_48e0_HBM00_AXI_nmu_0 || ORIG_REF_NAME==bd_48e0_HBM00_AXI_nmu_0} -quiet] {/bd_48e0_HBM00_AXI_nmu_0_top_INST } ]/bd_48e0_HBM00_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axi_noc_0_0/bd_0/ip/ip_5/hdl/par/bd_48e0_MC_hbmc_0_ip.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_48e0_MC_hbmc_0 || ORIG_REF_NAME==bd_48e0_MC_hbmc_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axi_noc_0_0/design_2_axi_noc_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_axi_noc_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axi_noc_0_0/design_2_axi_noc_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_axi_noc_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axi_noc_0_0/design_2_axi_noc_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_axi_noc_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
