# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/younas/Documents/Vivado/hbm_module_2_noc_tg_interface/hbm_module_2_noc_tg_interface.srcs/sources_1/bd/design_1/ip/design_1_noc_tg_pmon_2_0/design_1_noc_tg_pmon_2_0.xci
# IP: The module: 'design_1_noc_tg_pmon_2_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/younas/Documents/Vivado/hbm_module_2_noc_tg_interface/hbm_module_2_noc_tg_interface.gen/sources_1/bd/design_1/ip/design_1_noc_tg_pmon_2_0/hdl/par/design_1_noc_tg_pmon_2_0_ip.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_noc_tg_pmon_2_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2_noc_tg_interface/hbm_module_2_noc_tg_interface.srcs/sources_1/bd/design_1/ip/design_1_noc_tg_pmon_2_0/design_1_noc_tg_pmon_2_0.xci
# IP: The module: 'design_1_noc_tg_pmon_2_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/younas/Documents/Vivado/hbm_module_2_noc_tg_interface/hbm_module_2_noc_tg_interface.gen/sources_1/bd/design_1/ip/design_1_noc_tg_pmon_2_0/hdl/par/design_1_noc_tg_pmon_2_0_ip.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_noc_tg_pmon_2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
