/******************************************************************************
// (c) Copyright 2016 Xilinx, Inc. All rights reserved.
//
// This file contains confidential and proprietary information
// of Xilinx, Inc. and is protected under U.S. and
// international copyright and other intellectual property
// laws.
//
// DISCLAIMER
// This disclaimer is not a license and does not grant any
// rights to the materials distributed herewith. Except as
// otherwise provided in a valid license issued to you by
// Xilinx, and to the maximum extent permitted by applicable
// law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
// WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES
// AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
// BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
// INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
// (2) Xilinx shall not be liable (whether in contract or tort,
// including negligence, or under any other theory of
// liability) for any loss or damage of any kind or nature
// related to, arising under or in connection with these
// materials, including for any direct, or any indirect,
// special, incidental, or consequential loss or damage
// (including loss of data, profits, goodwill, or any type of
// loss or damage suffered as a result of any action brought
// by a third party) even if such damage or loss was
// reasonably foreseeable or Xilinx had been advised of the
// possibility of the same.
//
// CRITICAL APPLICATIONS
// Xilinx products are not designed or intended to be fail-
// safe, or for use in any application requiring fail-safe
// performance, such as life-support or safety devices or
// systems, Class III medical devices, nuclear facilities,
// applications related to the deployment of airbags, or any
// other applications that could lead to death, personal
// injury, or severe property or environmental damage
// (individually and collectively, "Critical
// Applications"). Customer assumes the sole risk and
// liability of any use of Xilinx products in Critical
// Applications, subject only to applicable laws and
// regulations governing limitations on product liability.
//
// THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
// PART OF THIS FILE AT ALL TIMES.
******************************************************************************/
//   ____  ____
//  /   /\/   /
// /___/  \  /    Vendor             : Xilinx
// \   \   \/     Version            : 1.0
//  \   \         Application        : NOC
//  /   /         Filename           : xlnoc_nps4_0_0.sv
// /___/   /\     Date Last Modified : $Date: 2020/07/01 $
// \   \  /  \    Date Created       : 
//  \___\/\___\
//
// Device           : Versal
// Design Name      : NPS4 (NoC Packet Switch 6)
// Purpose:
// 
//
// Reference        :
// Revision History :
//*****************************************************************************
`timescale 1ps/1ps

module xlnoc_nps4_0_0 
(
REQ_IN0_NOC_CREDIT_RETURN,
REQ_IN1_NOC_CREDIT_RETURN,
REQ_IN2_NOC_CREDIT_RETURN,
REQ_IN3_NOC_CREDIT_RETURN,
REQ_HBM_OUT0_NOC_CREDIT_RDY,
REQ_HBM_OUT0_NOC_FLIT,
REQ_HBM_OUT0_NOC_PDEST_ID,
REQ_HBM_OUT0_NOC_VALID,
REQ_HBM_OUT1_NOC_CREDIT_RDY,
REQ_HBM_OUT1_NOC_FLIT,
REQ_HBM_OUT1_NOC_PDEST_ID,
REQ_HBM_OUT1_NOC_VALID,
REQ_HBM_OUT2_NOC_CREDIT_RDY,
REQ_HBM_OUT2_NOC_FLIT,
REQ_HBM_OUT2_NOC_PDEST_ID,
REQ_HBM_OUT2_NOC_VALID,
REQ_HBM_OUT3_NOC_CREDIT_RDY,
REQ_HBM_OUT3_NOC_FLIT,
REQ_HBM_OUT3_NOC_PDEST_ID,
REQ_HBM_OUT3_NOC_VALID,
RESP_HBM_IN0_NOC_CREDIT_RETURN,
RESP_HBM_IN1_NOC_CREDIT_RETURN,
RESP_HBM_IN2_NOC_CREDIT_RETURN,
RESP_HBM_IN3_NOC_CREDIT_RETURN,
RESP_OUT0_NOC_CREDIT_RDY,
RESP_OUT0_NOC_FLIT,
RESP_OUT0_NOC_VALID,
RESP_OUT1_NOC_CREDIT_RDY,
RESP_OUT1_NOC_FLIT,
RESP_OUT1_NOC_VALID,
RESP_OUT2_NOC_CREDIT_RDY,
RESP_OUT2_NOC_FLIT,
RESP_OUT2_NOC_VALID,
RESP_OUT3_NOC_CREDIT_RDY,
RESP_OUT3_NOC_FLIT,
RESP_OUT3_NOC_VALID,
REQ_IN0_NOC_CREDIT_RDY,
REQ_IN0_NOC_FLIT,
REQ_IN0_NOC_VALID,
REQ_IN1_NOC_CREDIT_RDY,
REQ_IN1_NOC_FLIT,
REQ_IN1_NOC_VALID,
REQ_IN2_NOC_CREDIT_RDY,
REQ_IN2_NOC_FLIT,
REQ_IN2_NOC_VALID,
REQ_IN3_NOC_CREDIT_RDY,
REQ_IN3_NOC_FLIT,
REQ_IN3_NOC_VALID,
REQ_HBM_OUT0_NOC_CREDIT_RETURN,
REQ_HBM_OUT1_NOC_CREDIT_RETURN,
REQ_HBM_OUT2_NOC_CREDIT_RETURN,
REQ_HBM_OUT3_NOC_CREDIT_RETURN,
RESP_HBM_IN0_NOC_CREDIT_RDY,
RESP_HBM_IN0_NOC_FLIT,
RESP_HBM_IN0_NOC_PDEST_ID,
RESP_HBM_IN0_NOC_VALID,
RESP_HBM_IN1_NOC_CREDIT_RDY,
RESP_HBM_IN1_NOC_FLIT,
RESP_HBM_IN1_NOC_PDEST_ID,
RESP_HBM_IN1_NOC_VALID,
RESP_HBM_IN2_NOC_CREDIT_RDY,
RESP_HBM_IN2_NOC_FLIT,
RESP_HBM_IN2_NOC_PDEST_ID,
RESP_HBM_IN2_NOC_VALID,
RESP_HBM_IN3_NOC_CREDIT_RDY,
RESP_HBM_IN3_NOC_FLIT,
RESP_HBM_IN3_NOC_PDEST_ID,
RESP_HBM_IN3_NOC_VALID,
RESP_OUT0_NOC_CREDIT_RETURN,
RESP_OUT1_NOC_CREDIT_RETURN,
RESP_OUT2_NOC_CREDIT_RETURN,
RESP_OUT3_NOC_CREDIT_RETURN
);

output wire [7:0]   REQ_IN0_NOC_CREDIT_RETURN;
output wire [7:0]   REQ_IN1_NOC_CREDIT_RETURN;
output wire [7:0]   REQ_IN2_NOC_CREDIT_RETURN;
output wire [7:0]   REQ_IN3_NOC_CREDIT_RETURN;
output wire         REQ_HBM_OUT0_NOC_CREDIT_RDY;
output wire [181:0] REQ_HBM_OUT0_NOC_FLIT;
output wire [1:0]   REQ_HBM_OUT0_NOC_PDEST_ID;
output wire [7:0]   REQ_HBM_OUT0_NOC_VALID;
output wire         REQ_HBM_OUT1_NOC_CREDIT_RDY;
output wire [181:0] REQ_HBM_OUT1_NOC_FLIT;
output wire [1:0]   REQ_HBM_OUT1_NOC_PDEST_ID;
output wire [7:0]   REQ_HBM_OUT1_NOC_VALID;
output wire         REQ_HBM_OUT2_NOC_CREDIT_RDY;
output wire [181:0] REQ_HBM_OUT2_NOC_FLIT;
output wire [1:0]   REQ_HBM_OUT2_NOC_PDEST_ID;
output wire [7:0]   REQ_HBM_OUT2_NOC_VALID;
output wire         REQ_HBM_OUT3_NOC_CREDIT_RDY;
output wire [181:0] REQ_HBM_OUT3_NOC_FLIT;
output wire [1:0]   REQ_HBM_OUT3_NOC_PDEST_ID;
output wire [7:0]   REQ_HBM_OUT3_NOC_VALID;
output wire [7:0]   RESP_HBM_IN0_NOC_CREDIT_RETURN;
output wire [7:0]   RESP_HBM_IN1_NOC_CREDIT_RETURN;
output wire [7:0]   RESP_HBM_IN2_NOC_CREDIT_RETURN;
output wire [7:0]   RESP_HBM_IN3_NOC_CREDIT_RETURN;
output wire         RESP_OUT0_NOC_CREDIT_RDY;
output wire [181:0] RESP_OUT0_NOC_FLIT;
output wire [7:0]   RESP_OUT0_NOC_VALID;
output wire         RESP_OUT1_NOC_CREDIT_RDY;
output wire [181:0] RESP_OUT1_NOC_FLIT;
output wire [7:0]   RESP_OUT1_NOC_VALID;
output wire         RESP_OUT2_NOC_CREDIT_RDY;
output wire [181:0] RESP_OUT2_NOC_FLIT;
output wire [7:0]   RESP_OUT2_NOC_VALID;
output wire         RESP_OUT3_NOC_CREDIT_RDY;
output wire [181:0] RESP_OUT3_NOC_FLIT;
output wire [7:0]   RESP_OUT3_NOC_VALID;
input wire          REQ_IN0_NOC_CREDIT_RDY;
input wire [181:0]  REQ_IN0_NOC_FLIT;
input wire [7:0]    REQ_IN0_NOC_VALID;
input wire          REQ_IN1_NOC_CREDIT_RDY;
input wire [181:0]  REQ_IN1_NOC_FLIT;
input wire [7:0]    REQ_IN1_NOC_VALID;
input wire          REQ_IN2_NOC_CREDIT_RDY;
input wire [181:0]  REQ_IN2_NOC_FLIT;
input wire [7:0]    REQ_IN2_NOC_VALID;
input wire          REQ_IN3_NOC_CREDIT_RDY;
input wire [181:0]  REQ_IN3_NOC_FLIT;
input wire [7:0]    REQ_IN3_NOC_VALID;
input wire [7:0]    REQ_HBM_OUT0_NOC_CREDIT_RETURN;
input wire [7:0]    REQ_HBM_OUT1_NOC_CREDIT_RETURN;
input wire [7:0]    REQ_HBM_OUT2_NOC_CREDIT_RETURN;
input wire [7:0]    REQ_HBM_OUT3_NOC_CREDIT_RETURN;
input wire          RESP_HBM_IN0_NOC_CREDIT_RDY;
input wire [181:0]  RESP_HBM_IN0_NOC_FLIT;
input wire [1:0]    RESP_HBM_IN0_NOC_PDEST_ID;
input wire [7:0]    RESP_HBM_IN0_NOC_VALID;
input wire          RESP_HBM_IN1_NOC_CREDIT_RDY;
input wire [181:0]  RESP_HBM_IN1_NOC_FLIT;
input wire [1:0]    RESP_HBM_IN1_NOC_PDEST_ID;
input wire [7:0]    RESP_HBM_IN1_NOC_VALID;
input wire          RESP_HBM_IN2_NOC_CREDIT_RDY;
input wire [181:0]  RESP_HBM_IN2_NOC_FLIT;
input wire [1:0]    RESP_HBM_IN2_NOC_PDEST_ID;
input wire [7:0]    RESP_HBM_IN2_NOC_VALID;
input wire          RESP_HBM_IN3_NOC_CREDIT_RDY;
input wire [181:0]  RESP_HBM_IN3_NOC_FLIT;
input wire [1:0]    RESP_HBM_IN3_NOC_PDEST_ID;
input wire [7:0]    RESP_HBM_IN3_NOC_VALID;
input wire [7:0]    RESP_OUT0_NOC_CREDIT_RETURN;
input wire [7:0]    RESP_OUT1_NOC_CREDIT_RETURN;
input wire [7:0]    RESP_OUT2_NOC_CREDIT_RETURN;
input wire [7:0]    RESP_OUT3_NOC_CREDIT_RETURN;

xlnoc_nps4_0_0_nps4#(
.REG_DST_ID_P0 ('H080),
.REG_DST_ID_P1 ('H001),
.REG_DST_ID_P2 ('H001),
.REG_DST_ID_P3 ('H001),
.REG_HBM2NOC_P0_P0_VCA_TOKEN ('H10101010),
.REG_HBM2NOC_P0_P1_VCA_TOKEN ('H10101010),
.REG_HBM2NOC_P0_P2_VCA_TOKEN ('H10101010),
.REG_HBM2NOC_P0_P3_VCA_TOKEN ('H20ff1010),
.REG_HBM2NOC_P1_P0_VCA_TOKEN ('H10101010),
.REG_HBM2NOC_P1_P1_VCA_TOKEN ('H10101010),
.REG_HBM2NOC_P1_P2_VCA_TOKEN ('H10101010),
.REG_HBM2NOC_P1_P3_VCA_TOKEN ('H10101010),
.REG_HBM2NOC_P2_P0_VCA_TOKEN ('H10101010),
.REG_HBM2NOC_P2_P1_VCA_TOKEN ('H10101010),
.REG_HBM2NOC_P2_P2_VCA_TOKEN ('H10101010),
.REG_HBM2NOC_P2_P3_VCA_TOKEN ('H10101010),
.REG_HBM2NOC_P3_P0_VCA_TOKEN ('H10101010),
.REG_HBM2NOC_P3_P1_VCA_TOKEN ('H10101010),
.REG_HBM2NOC_P3_P2_VCA_TOKEN ('H10101010),
.REG_HBM2NOC_P3_P3_VCA_TOKEN ('H10101010),
.REG_NOC2HBM_P0_P0_VCA_TOKEN ('H10101010),
.REG_NOC2HBM_P0_P1_VCA_TOKEN ('H10101010),
.REG_NOC2HBM_P0_P2_VCA_TOKEN ('H10101010),
.REG_NOC2HBM_P0_P3_VCA_TOKEN ('H10101010),
.REG_NOC2HBM_P1_P0_VCA_TOKEN ('H10101010),
.REG_NOC2HBM_P1_P1_VCA_TOKEN ('H10101010),
.REG_NOC2HBM_P1_P2_VCA_TOKEN ('H10101010),
.REG_NOC2HBM_P1_P3_VCA_TOKEN ('H10101010),
.REG_NOC2HBM_P2_P0_VCA_TOKEN ('H10101010),
.REG_NOC2HBM_P2_P1_VCA_TOKEN ('H10101010),
.REG_NOC2HBM_P2_P2_VCA_TOKEN ('H10101010),
.REG_NOC2HBM_P2_P3_VCA_TOKEN ('H10101010),
.REG_NOC2HBM_P3_P0_VCA_TOKEN ('Hff1c1010),
.REG_NOC2HBM_P3_P1_VCA_TOKEN ('H10101010),
.REG_NOC2HBM_P3_P2_VCA_TOKEN ('H10101010),
.REG_NOC2HBM_P3_P3_VCA_TOKEN ('H10101010),
.REG_NOC_CTL ('H0)
) xlnoc_nps4_0_0_nps4_INST (
.REQ_IN0_NOC_CREDIT_RETURN (REQ_IN0_NOC_CREDIT_RETURN),
.REQ_IN1_NOC_CREDIT_RETURN (REQ_IN1_NOC_CREDIT_RETURN),
.REQ_IN2_NOC_CREDIT_RETURN (REQ_IN2_NOC_CREDIT_RETURN),
.REQ_IN3_NOC_CREDIT_RETURN (REQ_IN3_NOC_CREDIT_RETURN),
.REQ_HBM_OUT0_NOC_CREDIT_RDY (REQ_HBM_OUT0_NOC_CREDIT_RDY),
.REQ_HBM_OUT0_NOC_FLIT (REQ_HBM_OUT0_NOC_FLIT),
.REQ_HBM_OUT0_NOC_PDEST_ID (REQ_HBM_OUT0_NOC_PDEST_ID),
.REQ_HBM_OUT0_NOC_VALID (REQ_HBM_OUT0_NOC_VALID),
.REQ_HBM_OUT1_NOC_CREDIT_RDY (REQ_HBM_OUT1_NOC_CREDIT_RDY),
.REQ_HBM_OUT1_NOC_FLIT (REQ_HBM_OUT1_NOC_FLIT),
.REQ_HBM_OUT1_NOC_PDEST_ID (REQ_HBM_OUT1_NOC_PDEST_ID),
.REQ_HBM_OUT1_NOC_VALID (REQ_HBM_OUT1_NOC_VALID),
.REQ_HBM_OUT2_NOC_CREDIT_RDY (REQ_HBM_OUT2_NOC_CREDIT_RDY),
.REQ_HBM_OUT2_NOC_FLIT (REQ_HBM_OUT2_NOC_FLIT),
.REQ_HBM_OUT2_NOC_PDEST_ID (REQ_HBM_OUT2_NOC_PDEST_ID),
.REQ_HBM_OUT2_NOC_VALID (REQ_HBM_OUT2_NOC_VALID),
.REQ_HBM_OUT3_NOC_CREDIT_RDY (REQ_HBM_OUT3_NOC_CREDIT_RDY),
.REQ_HBM_OUT3_NOC_FLIT (REQ_HBM_OUT3_NOC_FLIT),
.REQ_HBM_OUT3_NOC_PDEST_ID (REQ_HBM_OUT3_NOC_PDEST_ID),
.REQ_HBM_OUT3_NOC_VALID (REQ_HBM_OUT3_NOC_VALID),
.RESP_HBM_IN0_NOC_CREDIT_RETURN (RESP_HBM_IN0_NOC_CREDIT_RETURN),
.RESP_HBM_IN1_NOC_CREDIT_RETURN (RESP_HBM_IN1_NOC_CREDIT_RETURN),
.RESP_HBM_IN2_NOC_CREDIT_RETURN (RESP_HBM_IN2_NOC_CREDIT_RETURN),
.RESP_HBM_IN3_NOC_CREDIT_RETURN (RESP_HBM_IN3_NOC_CREDIT_RETURN),
.RESP_OUT0_NOC_CREDIT_RDY (RESP_OUT0_NOC_CREDIT_RDY),
.RESP_OUT0_NOC_FLIT (RESP_OUT0_NOC_FLIT),
.RESP_OUT0_NOC_VALID (RESP_OUT0_NOC_VALID),
.RESP_OUT1_NOC_CREDIT_RDY (RESP_OUT1_NOC_CREDIT_RDY),
.RESP_OUT1_NOC_FLIT (RESP_OUT1_NOC_FLIT),
.RESP_OUT1_NOC_VALID (RESP_OUT1_NOC_VALID),
.RESP_OUT2_NOC_CREDIT_RDY (RESP_OUT2_NOC_CREDIT_RDY),
.RESP_OUT2_NOC_FLIT (RESP_OUT2_NOC_FLIT),
.RESP_OUT2_NOC_VALID (RESP_OUT2_NOC_VALID),
.RESP_OUT3_NOC_CREDIT_RDY (RESP_OUT3_NOC_CREDIT_RDY),
.RESP_OUT3_NOC_FLIT (RESP_OUT3_NOC_FLIT),
.RESP_OUT3_NOC_VALID (RESP_OUT3_NOC_VALID),
.REQ_IN0_NOC_CREDIT_RDY (REQ_IN0_NOC_CREDIT_RDY),
.REQ_IN0_NOC_FLIT (REQ_IN0_NOC_FLIT),
.REQ_IN0_NOC_VALID (REQ_IN0_NOC_VALID),
.REQ_IN1_NOC_CREDIT_RDY (REQ_IN1_NOC_CREDIT_RDY),
.REQ_IN1_NOC_FLIT (REQ_IN1_NOC_FLIT),
.REQ_IN1_NOC_VALID (REQ_IN1_NOC_VALID),
.REQ_IN2_NOC_CREDIT_RDY (REQ_IN2_NOC_CREDIT_RDY),
.REQ_IN2_NOC_FLIT (REQ_IN2_NOC_FLIT),
.REQ_IN2_NOC_VALID (REQ_IN2_NOC_VALID),
.REQ_IN3_NOC_CREDIT_RDY (REQ_IN3_NOC_CREDIT_RDY),
.REQ_IN3_NOC_FLIT (REQ_IN3_NOC_FLIT),
.REQ_IN3_NOC_VALID (REQ_IN3_NOC_VALID),
.REQ_HBM_OUT0_NOC_CREDIT_RETURN (REQ_HBM_OUT0_NOC_CREDIT_RETURN),
.REQ_HBM_OUT1_NOC_CREDIT_RETURN (REQ_HBM_OUT1_NOC_CREDIT_RETURN),
.REQ_HBM_OUT2_NOC_CREDIT_RETURN (REQ_HBM_OUT2_NOC_CREDIT_RETURN),
.REQ_HBM_OUT3_NOC_CREDIT_RETURN (REQ_HBM_OUT3_NOC_CREDIT_RETURN),
.RESP_HBM_IN0_NOC_CREDIT_RDY (RESP_HBM_IN0_NOC_CREDIT_RDY),
.RESP_HBM_IN0_NOC_FLIT (RESP_HBM_IN0_NOC_FLIT),
.RESP_HBM_IN0_NOC_PDEST_ID (RESP_HBM_IN0_NOC_PDEST_ID),
.RESP_HBM_IN0_NOC_VALID (RESP_HBM_IN0_NOC_VALID),
.RESP_HBM_IN1_NOC_CREDIT_RDY (RESP_HBM_IN1_NOC_CREDIT_RDY),
.RESP_HBM_IN1_NOC_FLIT (RESP_HBM_IN1_NOC_FLIT),
.RESP_HBM_IN1_NOC_PDEST_ID (RESP_HBM_IN1_NOC_PDEST_ID),
.RESP_HBM_IN1_NOC_VALID (RESP_HBM_IN1_NOC_VALID),
.RESP_HBM_IN2_NOC_CREDIT_RDY (RESP_HBM_IN2_NOC_CREDIT_RDY),
.RESP_HBM_IN2_NOC_FLIT (RESP_HBM_IN2_NOC_FLIT),
.RESP_HBM_IN2_NOC_PDEST_ID (RESP_HBM_IN2_NOC_PDEST_ID),
.RESP_HBM_IN2_NOC_VALID (RESP_HBM_IN2_NOC_VALID),
.RESP_HBM_IN3_NOC_CREDIT_RDY (RESP_HBM_IN3_NOC_CREDIT_RDY),
.RESP_HBM_IN3_NOC_FLIT (RESP_HBM_IN3_NOC_FLIT),
.RESP_HBM_IN3_NOC_PDEST_ID (RESP_HBM_IN3_NOC_PDEST_ID),
.RESP_HBM_IN3_NOC_VALID (RESP_HBM_IN3_NOC_VALID),
.RESP_OUT0_NOC_CREDIT_RETURN (RESP_OUT0_NOC_CREDIT_RETURN),
.RESP_OUT1_NOC_CREDIT_RETURN (RESP_OUT1_NOC_CREDIT_RETURN),
.RESP_OUT2_NOC_CREDIT_RETURN (RESP_OUT2_NOC_CREDIT_RETURN),
.RESP_OUT3_NOC_CREDIT_RETURN (RESP_OUT3_NOC_CREDIT_RETURN)
  );

endmodule
