# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/younas/Documents/Vivado/hbm_module_2_synth_impl/hbm_module_2_synth_impl.srcs/sources_1/bd/design_1/ip/design_1_noc_tg_0/design_1_noc_tg_0.xci
# IP: The module: 'design_1_noc_tg_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/younas/Documents/Vivado/hbm_module_2_synth_impl/hbm_module_2_synth_impl.gen/sources_1/bd/design_1/ip/design_1_noc_tg_0/ip_2/design_1_noc_tg_0_vip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_noc_tg_0_vip || ORIG_REF_NAME==design_1_noc_tg_0_vip} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2_synth_impl/hbm_module_2_synth_impl.gen/sources_1/bd/design_1/ip/design_1_noc_tg_0/ip_1/design_1_noc_tg_0_axi_register_slice_wronly.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_noc_tg_0_axi_register_slice_wronly || ORIG_REF_NAME==design_1_noc_tg_0_axi_register_slice_wronly} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2_synth_impl/hbm_module_2_synth_impl.gen/sources_1/bd/design_1/ip/design_1_noc_tg_0/ip_0/design_1_noc_tg_0_axi4_register_slice.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_noc_tg_0_axi4_register_slice || ORIG_REF_NAME==design_1_noc_tg_0_axi4_register_slice} -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2_synth_impl/hbm_module_2_synth_impl.gen/sources_1/bd/design_1/ip/design_1_noc_tg_0/ip_1/design_1_noc_tg_0_axi_register_slice_wronly_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_noc_tg_0_axi_register_slice_wronly || ORIG_REF_NAME==design_1_noc_tg_0_axi_register_slice_wronly} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2_synth_impl/hbm_module_2_synth_impl.gen/sources_1/bd/design_1/ip/design_1_noc_tg_0/ip_0/design_1_noc_tg_0_axi4_register_slice_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_noc_tg_0_axi4_register_slice || ORIG_REF_NAME==design_1_noc_tg_0_axi4_register_slice} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2_synth_impl/hbm_module_2_synth_impl.gen/sources_1/bd/design_1/ip/design_1_noc_tg_0/hdl/par/design_1_noc_tg_0_ip.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_noc_tg_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2_synth_impl/hbm_module_2_synth_impl.gen/sources_1/bd/design_1/ip/design_1_noc_tg_0/par/design_1_noc_tg_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_noc_tg_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2_synth_impl/hbm_module_2_synth_impl.srcs/sources_1/bd/design_1/ip/design_1_noc_tg_0/design_1_noc_tg_0.xci
# IP: The module: 'design_1_noc_tg_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/younas/Documents/Vivado/hbm_module_2_synth_impl/hbm_module_2_synth_impl.gen/sources_1/bd/design_1/ip/design_1_noc_tg_0/ip_2/design_1_noc_tg_0_vip.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_noc_tg_0_vip || ORIG_REF_NAME==design_1_noc_tg_0_vip} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2_synth_impl/hbm_module_2_synth_impl.gen/sources_1/bd/design_1/ip/design_1_noc_tg_0/ip_1/design_1_noc_tg_0_axi_register_slice_wronly.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_noc_tg_0_axi_register_slice_wronly || ORIG_REF_NAME==design_1_noc_tg_0_axi_register_slice_wronly} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2_synth_impl/hbm_module_2_synth_impl.gen/sources_1/bd/design_1/ip/design_1_noc_tg_0/ip_0/design_1_noc_tg_0_axi4_register_slice.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_noc_tg_0_axi4_register_slice || ORIG_REF_NAME==design_1_noc_tg_0_axi4_register_slice} -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2_synth_impl/hbm_module_2_synth_impl.gen/sources_1/bd/design_1/ip/design_1_noc_tg_0/ip_1/design_1_noc_tg_0_axi_register_slice_wronly_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_noc_tg_0_axi_register_slice_wronly || ORIG_REF_NAME==design_1_noc_tg_0_axi_register_slice_wronly} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2_synth_impl/hbm_module_2_synth_impl.gen/sources_1/bd/design_1/ip/design_1_noc_tg_0/ip_0/design_1_noc_tg_0_axi4_register_slice_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_noc_tg_0_axi4_register_slice || ORIG_REF_NAME==design_1_noc_tg_0_axi4_register_slice} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2_synth_impl/hbm_module_2_synth_impl.gen/sources_1/bd/design_1/ip/design_1_noc_tg_0/hdl/par/design_1_noc_tg_0_ip.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_noc_tg_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2_synth_impl/hbm_module_2_synth_impl.gen/sources_1/bd/design_1/ip/design_1_noc_tg_0/par/design_1_noc_tg_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_noc_tg_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
