# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_noc_0_0/design_1_axi_noc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_noc_0_0 || ORIG_REF_NAME==design_1_axi_noc_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_noc_clk_gen_0/design_1_noc_clk_gen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_noc_clk_gen_0 || ORIG_REF_NAME==design_1_noc_clk_gen_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_noc_tg_0/design_1_noc_tg_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_noc_tg_0 || ORIG_REF_NAME==design_1_noc_tg_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_noc_sim_trig_0/design_1_noc_sim_trig_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_noc_sim_trig_0 || ORIG_REF_NAME==design_1_noc_sim_trig_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_noc_tg_pmon_0/design_1_noc_tg_pmon_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_noc_tg_pmon_0 || ORIG_REF_NAME==design_1_noc_tg_pmon_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_0/design_1_clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0 || ORIG_REF_NAME==design_1_clk_wiz_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_clk_wiz_100M_0/design_1_rst_clk_wiz_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_rst_clk_wiz_100M_0 || ORIG_REF_NAME==design_1_rst_clk_wiz_100M_0} -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_1/hbm_module_1.gen/sources_1/bd/design_1/design_1_ooc.xdc
