# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/younas/Documents/Vivado/hbm_module_1/hbm_module_1.srcs/sources_1/bd/design_1/ip/design_1_noc_sim_trig_0/design_1_noc_sim_trig_0.xci
# IP: The module: 'design_1_noc_sim_trig_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/younas/Documents/Vivado/hbm_module_1/hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_noc_sim_trig_0/ip_0/axi_apb_bridge_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_apb_bridge_0 || ORIG_REF_NAME==axi_apb_bridge_0} -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_1/hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_noc_sim_trig_0/ip_0/axi_apb_bridge_0_ooc.xdc

# XDC: /home/younas/Documents/Vivado/hbm_module_1/hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_noc_sim_trig_0/hdl/par/design_1_noc_sim_trig_0_ip.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_noc_sim_trig_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_1/hbm_module_1.srcs/sources_1/bd/design_1/ip/design_1_noc_sim_trig_0/design_1_noc_sim_trig_0.xci
# IP: The module: 'design_1_noc_sim_trig_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/younas/Documents/Vivado/hbm_module_1/hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_noc_sim_trig_0/ip_0/axi_apb_bridge_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_apb_bridge_0 || ORIG_REF_NAME==axi_apb_bridge_0} -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_1/hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_noc_sim_trig_0/ip_0/axi_apb_bridge_0_ooc.xdc

# XDC: /home/younas/Documents/Vivado/hbm_module_1/hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_noc_sim_trig_0/hdl/par/design_1_noc_sim_trig_0_ip.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_noc_sim_trig_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
