#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2024.2 (64-bit)
#
# Filename    : compile.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for compiling the simulation design source files
#
# Generated by Vivado on Mon May 05 19:36:46 PKT 2025
# SW Build 5239630 on Fri Nov 08 22:34:34 MST 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: compile.sh
#
# ****************************************************************************
set -Eeuo pipefail
# compile Verilog/System Verilog design sources
echo "xvlog --incr --relax -L uvm -L clk_gen_sim_v1_0_4 -L sim_trig_v1_0_13 -L axi4stream_vip_v1_1_19 -L axi_vip_v1_1_19 -L perf_axi_tg_v1_0_15 -L axi_pmon_v1_0_2 -L cpm5_v1_0_17 -L cpm4_v1_0_17 -L noc_nps4_v1_0_0 -L noc_nps6_v1_0_0 -L axis_vio_v1_0_12 -L noc_hbm_nmu_sim_v1_0_0 -L noc_nmu_sim_v1_0_0 -L noc_hbm_v1_0_1 -L smartconnect_v1_0 -L versal_cips_ps_vip_v1_0_11 -L xilinx_vip -prj design_1_wrapper_sim_wrapper_vlog.prj"
xvlog --incr --relax -L uvm -L clk_gen_sim_v1_0_4 -L sim_trig_v1_0_13 -L axi4stream_vip_v1_1_19 -L axi_vip_v1_1_19 -L perf_axi_tg_v1_0_15 -L axi_pmon_v1_0_2 -L cpm5_v1_0_17 -L cpm4_v1_0_17 -L noc_nps4_v1_0_0 -L noc_nps6_v1_0_0 -L axis_vio_v1_0_12 -L noc_hbm_nmu_sim_v1_0_0 -L noc_nmu_sim_v1_0_0 -L noc_hbm_v1_0_1 -L smartconnect_v1_0 -L versal_cips_ps_vip_v1_0_11 -L xilinx_vip -prj design_1_wrapper_sim_wrapper_vlog.prj 2>&1 | tee compile.log

# compile VHDL design sources
echo "xvhdl --incr --relax -prj design_1_wrapper_sim_wrapper_vhdl.prj"
xvhdl --incr --relax -prj design_1_wrapper_sim_wrapper_vhdl.prj 2>&1 | tee -a compile.log

echo "Waiting for jobs to finish..."
echo "No pending jobs, compilation finished."
