#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2024.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Mon May 05 17:10:41 PKT 2025
# SW Build 5239630 on Fri Nov 08 22:34:34 MST 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail

# resolve compiled library path in xsim.ini
export RDI_DATADIR="/tools/Xilinx/Vivado/2024.2/data"

# elaborate design
echo "xelab --incr --debug typical --relax --mt 8 -L xil_defaultlib -L noc_nps4_v1_0_0 -L noc_nps6_v1_0_0 -L noc_nmu_sim_v1_0_0 -L noc_hbm_nmu_sim_v1_0_0 -L xlconstant_v1_1_9 -L noc_hbm_v1_0_1 -L clk_gen_sim_v1_0_4 -L axi_infrastructure_v1_1_0 -L axi_register_slice_v2_1_33 -L axi_vip_v1_1_19 -L axis_infrastructure_v1_1_1 -L axi4stream_vip_v1_1_19 -L perf_axi_tg_v1_0_15 -L lib_pkg_v1_0_4 -L axi_apb_bridge_v3_0_20 -L sim_trig_v1_0_13 -L axi_pmon_v1_0_2 -L axis_dbg_stub_v1_0_1 -L axis_dbg_sync_v1_0_1 -L axis_vio_v1_0_12 -L smartconnect_v1_0 -L lib_cdc_v1_0_3 -L proc_sys_reset_v5_0_16 -L versal_cips_ps_vip_v1_0_11 -L cpm4_v1_0_17 -L cpm5_v1_0_17 -L xlconcat_v2_1_6 -L axis_ila_intf_v1_0_2 -L axis_cap_ctrl_v1_0_1 -L axis_mu_v1_0_1 -L axis_itct_v1_0_1 -L axis_ila_pp_v1_0_2 -L axis_mem_v1_0_2 -L uvm -L xilinx_vip -L unisims_ver -L unimacro_ver -L unisims_ver -L secureip -L xpm --snapshot design_1_wrapper_sim_wrapper_behav xil_defaultlib.design_1_wrapper_sim_wrapper xil_defaultlib.glbl -log elaborate.log"
xelab --incr --debug typical --relax --mt 8 -L xil_defaultlib -L noc_nps4_v1_0_0 -L noc_nps6_v1_0_0 -L noc_nmu_sim_v1_0_0 -L noc_hbm_nmu_sim_v1_0_0 -L xlconstant_v1_1_9 -L noc_hbm_v1_0_1 -L clk_gen_sim_v1_0_4 -L axi_infrastructure_v1_1_0 -L axi_register_slice_v2_1_33 -L axi_vip_v1_1_19 -L axis_infrastructure_v1_1_1 -L axi4stream_vip_v1_1_19 -L perf_axi_tg_v1_0_15 -L lib_pkg_v1_0_4 -L axi_apb_bridge_v3_0_20 -L sim_trig_v1_0_13 -L axi_pmon_v1_0_2 -L axis_dbg_stub_v1_0_1 -L axis_dbg_sync_v1_0_1 -L axis_vio_v1_0_12 -L smartconnect_v1_0 -L lib_cdc_v1_0_3 -L proc_sys_reset_v5_0_16 -L versal_cips_ps_vip_v1_0_11 -L cpm4_v1_0_17 -L cpm5_v1_0_17 -L xlconcat_v2_1_6 -L axis_ila_intf_v1_0_2 -L axis_cap_ctrl_v1_0_1 -L axis_mu_v1_0_1 -L axis_itct_v1_0_1 -L axis_ila_pp_v1_0_2 -L axis_mem_v1_0_2 -L uvm -L xilinx_vip -L unisims_ver -L unimacro_ver -L unisims_ver -L secureip -L xpm --snapshot design_1_wrapper_sim_wrapper_behav xil_defaultlib.design_1_wrapper_sim_wrapper xil_defaultlib.glbl -log elaborate.log

