///////////////////////////////////////////////////////////////////////////
//NOTE: This file has been automatically generated by Vivado.
///////////////////////////////////////////////////////////////////////////
`timescale 1ps/1ps
package design_2_noc_tg_1_0_vip_pkg;
import axi_vip_pkg::*;
///////////////////////////////////////////////////////////////////////////
// These parameters are named after the component for use in your verification 
// environment.
///////////////////////////////////////////////////////////////////////////
      parameter design_2_noc_tg_1_0_vip_VIP_PROTOCOL           = 0;
      parameter design_2_noc_tg_1_0_vip_VIP_READ_WRITE_MODE    = "READ_WRITE";
      parameter design_2_noc_tg_1_0_vip_VIP_INTERFACE_MODE     = 0;
      parameter design_2_noc_tg_1_0_vip_VIP_ADDR_WIDTH         = 64;
      parameter design_2_noc_tg_1_0_vip_VIP_DATA_WIDTH         = 256;
      parameter design_2_noc_tg_1_0_vip_VIP_ID_WIDTH           = 7;
      parameter design_2_noc_tg_1_0_vip_VIP_AWUSER_WIDTH       = 16;
      parameter design_2_noc_tg_1_0_vip_VIP_ARUSER_WIDTH       = 16;
      parameter design_2_noc_tg_1_0_vip_VIP_RUSER_WIDTH        = 16;
      parameter design_2_noc_tg_1_0_vip_VIP_WUSER_WIDTH        = 16;
      parameter design_2_noc_tg_1_0_vip_VIP_BUSER_WIDTH        = 16;
      parameter design_2_noc_tg_1_0_vip_VIP_SUPPORTS_NARROW    = 1;
      parameter design_2_noc_tg_1_0_vip_VIP_HAS_BURST          = 1;
      parameter design_2_noc_tg_1_0_vip_VIP_HAS_LOCK           = 1;
      parameter design_2_noc_tg_1_0_vip_VIP_HAS_CACHE          = 1;
      parameter design_2_noc_tg_1_0_vip_VIP_HAS_REGION         = 1;
      parameter design_2_noc_tg_1_0_vip_VIP_HAS_QOS            = 1;
      parameter design_2_noc_tg_1_0_vip_VIP_HAS_PROT           = 1;
      parameter design_2_noc_tg_1_0_vip_VIP_HAS_WSTRB          = 1;
      parameter design_2_noc_tg_1_0_vip_VIP_HAS_BRESP          = 1;
      parameter design_2_noc_tg_1_0_vip_VIP_HAS_RRESP          = 1;
      parameter design_2_noc_tg_1_0_vip_VIP_HAS_ACLKEN         = 0;
      parameter design_2_noc_tg_1_0_vip_VIP_HAS_ARESETN        = 1;
///////////////////////////////////////////////////////////////////////////
typedef axi_mst_agent #(design_2_noc_tg_1_0_vip_VIP_PROTOCOL, 
                        design_2_noc_tg_1_0_vip_VIP_ADDR_WIDTH,
                        design_2_noc_tg_1_0_vip_VIP_DATA_WIDTH,
                        design_2_noc_tg_1_0_vip_VIP_DATA_WIDTH,
                        design_2_noc_tg_1_0_vip_VIP_ID_WIDTH,
                        design_2_noc_tg_1_0_vip_VIP_ID_WIDTH,
                        design_2_noc_tg_1_0_vip_VIP_AWUSER_WIDTH, 
                        design_2_noc_tg_1_0_vip_VIP_WUSER_WIDTH, 
                        design_2_noc_tg_1_0_vip_VIP_BUSER_WIDTH, 
                        design_2_noc_tg_1_0_vip_VIP_ARUSER_WIDTH,
                        design_2_noc_tg_1_0_vip_VIP_RUSER_WIDTH, 
                        design_2_noc_tg_1_0_vip_VIP_SUPPORTS_NARROW, 
                        design_2_noc_tg_1_0_vip_VIP_HAS_BURST,
                        design_2_noc_tg_1_0_vip_VIP_HAS_LOCK,
                        design_2_noc_tg_1_0_vip_VIP_HAS_CACHE,
                        design_2_noc_tg_1_0_vip_VIP_HAS_REGION,
                        design_2_noc_tg_1_0_vip_VIP_HAS_PROT,
                        design_2_noc_tg_1_0_vip_VIP_HAS_QOS,
                        design_2_noc_tg_1_0_vip_VIP_HAS_WSTRB,
                        design_2_noc_tg_1_0_vip_VIP_HAS_BRESP,
                        design_2_noc_tg_1_0_vip_VIP_HAS_RRESP,
                        design_2_noc_tg_1_0_vip_VIP_HAS_ARESETN) design_2_noc_tg_1_0_vip_mst_t;
      
///////////////////////////////////////////////////////////////////////////
// How to start the verification component
///////////////////////////////////////////////////////////////////////////
//      design_2_noc_tg_1_0_vip_mst_t  design_2_noc_tg_1_0_vip_mst;
//      initial begin : START_design_2_noc_tg_1_0_vip_MASTER
//        design_2_noc_tg_1_0_vip_mst = new("design_2_noc_tg_1_0_vip_mst", `design_2_noc_tg_1_0_vip_PATH_TO_INTERFACE);
//        design_2_noc_tg_1_0_vip_mst.start_master();
//      end



endpackage : design_2_noc_tg_1_0_vip_pkg
