set_property SRC_FILE_INFO {cfile:/home/younas/Documents/Vivado/hbm_module_2/hbm_module_2_noc_tg_interface.runs/design_1_noc_tg_1_0_synth_1/dont_touch.xdc rfile:../../../dont_touch.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells inst/u_top_axi_mst/u_tg_top/gen_axi4_reg_slice.u_axi_register_slice_wrOnly_0/inst]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells inst/u_top_axi_mst/u_tg_top/gen_axi4_reg_slice.u_axi_register_slice_wrOnly_1/inst]
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells inst/u_top_axi_mst/u_tg_top/gen_axi4_reg_slice.u_axi4_reg_slice/inst]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells inst]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells inst/u_top_axi_mst/u_tg_top/gen_axi4_reg_slice.u_axi_register_slice_wrOnly_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells inst/u_top_axi_mst/u_tg_top/gen_axi4_reg_slice.u_axi_register_slice_wrOnly_1]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells inst/u_top_axi_mst/u_tg_top/gen_axi4_reg_slice.u_axi4_reg_slice]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells inst/u_top_axi_mst/u_tg_top/u_axi_inst_core/xpm_memory_sdpram_inst]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells inst/u_top_axi_mst/u_tg_top/u_axi_inst_core/u_wr_ch_fifo/xpm_memory_sdpram_inst]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells inst/u_top_axi_mst/u_tg_top/u_axi_inst_core/u_rd_ch_fifo/xpm_memory_sdpram_inst]
