# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.srcs/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/design_2_axis_ila_0_0.xci
# IP: The module: 'design_2_axis_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/bd_4608.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608 || ORIG_REF_NAME==bd_4608} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_0/bd_4608_slot_0_aw_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_slot_0_aw_0 || ORIG_REF_NAME==bd_4608_slot_0_aw_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_1/bd_4608_slot_0_w_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_slot_0_w_0 || ORIG_REF_NAME==bd_4608_slot_0_w_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_2/bd_4608_slot_0_b_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_slot_0_b_0 || ORIG_REF_NAME==bd_4608_slot_0_b_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_3/bd_4608_slot_0_ar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_slot_0_ar_0 || ORIG_REF_NAME==bd_4608_slot_0_ar_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_4/bd_4608_slot_0_r_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_slot_0_r_0 || ORIG_REF_NAME==bd_4608_slot_0_r_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_5/bd_4608_axis_dbg_stub_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_dbg_stub_0 || ORIG_REF_NAME==bd_4608_axis_dbg_stub_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_6/bd_4608_xlconstant_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_xlconstant_0 || ORIG_REF_NAME==bd_4608_xlconstant_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_7/bd_4608_axis_ila_intf_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_ila_intf_0 || ORIG_REF_NAME==bd_4608_axis_ila_intf_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_8/bd_4608_axis_cap_ctrl_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_cap_ctrl_0 || ORIG_REF_NAME==bd_4608_axis_cap_ctrl_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_9/bd_4608_axis_mu0_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu0_0_0 || ORIG_REF_NAME==bd_4608_axis_mu0_0_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_10/bd_4608_axis_mu1_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu1_0_0 || ORIG_REF_NAME==bd_4608_axis_mu1_0_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_11/bd_4608_axis_mu2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu2_0_0 || ORIG_REF_NAME==bd_4608_axis_mu2_0_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_12/bd_4608_axis_mu3_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu3_0_0 || ORIG_REF_NAME==bd_4608_axis_mu3_0_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_13/bd_4608_axis_mu4_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu4_0_0 || ORIG_REF_NAME==bd_4608_axis_mu4_0_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_14/bd_4608_axis_mu5_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu5_0_0 || ORIG_REF_NAME==bd_4608_axis_mu5_0_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_15/bd_4608_axis_mu6_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu6_0_0 || ORIG_REF_NAME==bd_4608_axis_mu6_0_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_16/bd_4608_axis_mu7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu7_0_0 || ORIG_REF_NAME==bd_4608_axis_mu7_0_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_17/bd_4608_axis_mu8_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu8_0_0 || ORIG_REF_NAME==bd_4608_axis_mu8_0_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_18/bd_4608_axis_mu9_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu9_0_0 || ORIG_REF_NAME==bd_4608_axis_mu9_0_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_19/bd_4608_axis_mu10_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu10_0_0 || ORIG_REF_NAME==bd_4608_axis_mu10_0_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_20/bd_4608_axis_mu11_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu11_0_0 || ORIG_REF_NAME==bd_4608_axis_mu11_0_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_21/bd_4608_axis_mu12_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu12_0_0 || ORIG_REF_NAME==bd_4608_axis_mu12_0_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_22/bd_4608_axis_mu13_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu13_0_0 || ORIG_REF_NAME==bd_4608_axis_mu13_0_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_23/bd_4608_axis_mu14_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu14_0_0 || ORIG_REF_NAME==bd_4608_axis_mu14_0_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_24/bd_4608_axis_mu15_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu15_0_0 || ORIG_REF_NAME==bd_4608_axis_mu15_0_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_25/bd_4608_axis_mu16_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu16_0_0 || ORIG_REF_NAME==bd_4608_axis_mu16_0_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_26/bd_4608_axis_mu17_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu17_0_0 || ORIG_REF_NAME==bd_4608_axis_mu17_0_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_27/bd_4608_axis_mu18_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu18_0_0 || ORIG_REF_NAME==bd_4608_axis_mu18_0_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_28/bd_4608_axis_mu19_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu19_0_0 || ORIG_REF_NAME==bd_4608_axis_mu19_0_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_29/bd_4608_axis_mu20_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu20_0_0 || ORIG_REF_NAME==bd_4608_axis_mu20_0_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_30/bd_4608_axis_mu21_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu21_0_0 || ORIG_REF_NAME==bd_4608_axis_mu21_0_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_31/bd_4608_axis_mu22_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu22_0_0 || ORIG_REF_NAME==bd_4608_axis_mu22_0_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_32/bd_4608_axis_mu23_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu23_0_0 || ORIG_REF_NAME==bd_4608_axis_mu23_0_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_33/bd_4608_axis_mu24_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu24_0_0 || ORIG_REF_NAME==bd_4608_axis_mu24_0_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_34/bd_4608_axis_mu25_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu25_0_0 || ORIG_REF_NAME==bd_4608_axis_mu25_0_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_35/bd_4608_axis_mu26_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu26_0_0 || ORIG_REF_NAME==bd_4608_axis_mu26_0_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_36/bd_4608_axis_mu27_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu27_0_0 || ORIG_REF_NAME==bd_4608_axis_mu27_0_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_37/bd_4608_axis_mu28_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu28_0_0 || ORIG_REF_NAME==bd_4608_axis_mu28_0_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_38/bd_4608_axis_mu29_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu29_0_0 || ORIG_REF_NAME==bd_4608_axis_mu29_0_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_39/bd_4608_axis_mu30_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu30_0_0 || ORIG_REF_NAME==bd_4608_axis_mu30_0_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_40/bd_4608_axis_mu31_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu31_0_0 || ORIG_REF_NAME==bd_4608_axis_mu31_0_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_41/bd_4608_axis_mu32_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu32_0_0 || ORIG_REF_NAME==bd_4608_axis_mu32_0_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_42/bd_4608_axis_mu33_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu33_0_0 || ORIG_REF_NAME==bd_4608_axis_mu33_0_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_43/bd_4608_axis_mu34_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu34_0_0 || ORIG_REF_NAME==bd_4608_axis_mu34_0_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_44/bd_4608_axis_mu35_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu35_0_0 || ORIG_REF_NAME==bd_4608_axis_mu35_0_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_45/bd_4608_axis_mu36_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu36_0_0 || ORIG_REF_NAME==bd_4608_axis_mu36_0_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_46/bd_4608_axis_dbg_sync_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_dbg_sync_2_0 || ORIG_REF_NAME==bd_4608_axis_dbg_sync_2_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_47/bd_4608_axis_dbg_sync_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_dbg_sync_3_0 || ORIG_REF_NAME==bd_4608_axis_dbg_sync_3_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_48/bd_4608_axis_dbg_sync_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_dbg_sync_4_0 || ORIG_REF_NAME==bd_4608_axis_dbg_sync_4_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_49/bd_4608_axis_dbg_sync_5_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_dbg_sync_5_0 || ORIG_REF_NAME==bd_4608_axis_dbg_sync_5_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_50/bd_4608_axis_dbg_sync_6_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_dbg_sync_6_0 || ORIG_REF_NAME==bd_4608_axis_dbg_sync_6_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_51/bd_4608_tc_axis_mu0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_tc_axis_mu0_0 || ORIG_REF_NAME==bd_4608_tc_axis_mu0_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_52/bd_4608_cc_axis_mu0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_cc_axis_mu0_0 || ORIG_REF_NAME==bd_4608_cc_axis_mu0_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_53/bd_4608_cc_axis_mu1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_cc_axis_mu1_0 || ORIG_REF_NAME==bd_4608_cc_axis_mu1_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_54/bd_4608_cc_axis_mu2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_cc_axis_mu2_0 || ORIG_REF_NAME==bd_4608_cc_axis_mu2_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_55/bd_4608_cc_axis_mu3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_cc_axis_mu3_0 || ORIG_REF_NAME==bd_4608_cc_axis_mu3_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_56/bd_4608_axis_itct_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_itct_0 || ORIG_REF_NAME==bd_4608_axis_itct_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_57/bd_4608_axis_ila_pp_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_ila_pp_0 || ORIG_REF_NAME==bd_4608_axis_ila_pp_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_58/bd_4608_axis_mem_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_mem_0 || ORIG_REF_NAME==bd_4608_axis_mem_0} -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_9/axis_mu_v1_0/constraints/axis_mu_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu0_0_0 || ORIG_REF_NAME==bd_4608_axis_mu0_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_10/axis_mu_v1_0/constraints/axis_mu_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu1_0_0 || ORIG_REF_NAME==bd_4608_axis_mu1_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_11/axis_mu_v1_0/constraints/axis_mu_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu2_0_0 || ORIG_REF_NAME==bd_4608_axis_mu2_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_12/axis_mu_v1_0/constraints/axis_mu_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu3_0_0 || ORIG_REF_NAME==bd_4608_axis_mu3_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_13/axis_mu_v1_0/constraints/axis_mu_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu4_0_0 || ORIG_REF_NAME==bd_4608_axis_mu4_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_14/axis_mu_v1_0/constraints/axis_mu_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu5_0_0 || ORIG_REF_NAME==bd_4608_axis_mu5_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_15/axis_mu_v1_0/constraints/axis_mu_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu6_0_0 || ORIG_REF_NAME==bd_4608_axis_mu6_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_16/axis_mu_v1_0/constraints/axis_mu_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu7_0_0 || ORIG_REF_NAME==bd_4608_axis_mu7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_17/axis_mu_v1_0/constraints/axis_mu_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu8_0_0 || ORIG_REF_NAME==bd_4608_axis_mu8_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_18/axis_mu_v1_0/constraints/axis_mu_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu9_0_0 || ORIG_REF_NAME==bd_4608_axis_mu9_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_19/axis_mu_v1_0/constraints/axis_mu_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu10_0_0 || ORIG_REF_NAME==bd_4608_axis_mu10_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_20/axis_mu_v1_0/constraints/axis_mu_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu11_0_0 || ORIG_REF_NAME==bd_4608_axis_mu11_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_21/axis_mu_v1_0/constraints/axis_mu_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu12_0_0 || ORIG_REF_NAME==bd_4608_axis_mu12_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_22/axis_mu_v1_0/constraints/axis_mu_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu13_0_0 || ORIG_REF_NAME==bd_4608_axis_mu13_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_23/axis_mu_v1_0/constraints/axis_mu_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu14_0_0 || ORIG_REF_NAME==bd_4608_axis_mu14_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_24/axis_mu_v1_0/constraints/axis_mu_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu15_0_0 || ORIG_REF_NAME==bd_4608_axis_mu15_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_25/axis_mu_v1_0/constraints/axis_mu_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu16_0_0 || ORIG_REF_NAME==bd_4608_axis_mu16_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_26/axis_mu_v1_0/constraints/axis_mu_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu17_0_0 || ORIG_REF_NAME==bd_4608_axis_mu17_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_27/axis_mu_v1_0/constraints/axis_mu_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu18_0_0 || ORIG_REF_NAME==bd_4608_axis_mu18_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_28/axis_mu_v1_0/constraints/axis_mu_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu19_0_0 || ORIG_REF_NAME==bd_4608_axis_mu19_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_29/axis_mu_v1_0/constraints/axis_mu_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu20_0_0 || ORIG_REF_NAME==bd_4608_axis_mu20_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_30/axis_mu_v1_0/constraints/axis_mu_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu21_0_0 || ORIG_REF_NAME==bd_4608_axis_mu21_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_31/axis_mu_v1_0/constraints/axis_mu_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu22_0_0 || ORIG_REF_NAME==bd_4608_axis_mu22_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_32/axis_mu_v1_0/constraints/axis_mu_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu23_0_0 || ORIG_REF_NAME==bd_4608_axis_mu23_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_33/axis_mu_v1_0/constraints/axis_mu_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu24_0_0 || ORIG_REF_NAME==bd_4608_axis_mu24_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_34/axis_mu_v1_0/constraints/axis_mu_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu25_0_0 || ORIG_REF_NAME==bd_4608_axis_mu25_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_35/axis_mu_v1_0/constraints/axis_mu_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu26_0_0 || ORIG_REF_NAME==bd_4608_axis_mu26_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_36/axis_mu_v1_0/constraints/axis_mu_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu27_0_0 || ORIG_REF_NAME==bd_4608_axis_mu27_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_37/axis_mu_v1_0/constraints/axis_mu_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu28_0_0 || ORIG_REF_NAME==bd_4608_axis_mu28_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_38/axis_mu_v1_0/constraints/axis_mu_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu29_0_0 || ORIG_REF_NAME==bd_4608_axis_mu29_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_39/axis_mu_v1_0/constraints/axis_mu_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu30_0_0 || ORIG_REF_NAME==bd_4608_axis_mu30_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_40/axis_mu_v1_0/constraints/axis_mu_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu31_0_0 || ORIG_REF_NAME==bd_4608_axis_mu31_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_41/axis_mu_v1_0/constraints/axis_mu_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu32_0_0 || ORIG_REF_NAME==bd_4608_axis_mu32_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_42/axis_mu_v1_0/constraints/axis_mu_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu33_0_0 || ORIG_REF_NAME==bd_4608_axis_mu33_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_43/axis_mu_v1_0/constraints/axis_mu_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu34_0_0 || ORIG_REF_NAME==bd_4608_axis_mu34_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_44/axis_mu_v1_0/constraints/axis_mu_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu35_0_0 || ORIG_REF_NAME==bd_4608_axis_mu35_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_45/axis_mu_v1_0/constraints/axis_mu_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu36_0_0 || ORIG_REF_NAME==bd_4608_axis_mu36_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_51/axis_mu_v1_0/constraints/axis_mu_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_4608_tc_axis_mu0_0 || ORIG_REF_NAME==bd_4608_tc_axis_mu0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_52/axis_mu_v1_0/constraints/axis_mu_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_4608_cc_axis_mu0_0 || ORIG_REF_NAME==bd_4608_cc_axis_mu0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_53/axis_mu_v1_0/constraints/axis_mu_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_4608_cc_axis_mu1_0 || ORIG_REF_NAME==bd_4608_cc_axis_mu1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_54/axis_mu_v1_0/constraints/axis_mu_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_4608_cc_axis_mu2_0 || ORIG_REF_NAME==bd_4608_cc_axis_mu2_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_55/axis_mu_v1_0/constraints/axis_mu_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_4608_cc_axis_mu3_0 || ORIG_REF_NAME==bd_4608_cc_axis_mu3_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/bd_4608_ooc.xdc

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/axis_ila_v1_3/constraints/axis_ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_axis_ila_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/axis_ila_v1_3/constraints/axis_ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_axis_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/design_2_axis_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_axis_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.srcs/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/design_2_axis_ila_0_0.xci
# IP: The module: 'design_2_axis_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/bd_4608.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608 || ORIG_REF_NAME==bd_4608} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_0/bd_4608_slot_0_aw_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_slot_0_aw_0 || ORIG_REF_NAME==bd_4608_slot_0_aw_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_1/bd_4608_slot_0_w_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_slot_0_w_0 || ORIG_REF_NAME==bd_4608_slot_0_w_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_2/bd_4608_slot_0_b_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_slot_0_b_0 || ORIG_REF_NAME==bd_4608_slot_0_b_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_3/bd_4608_slot_0_ar_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_slot_0_ar_0 || ORIG_REF_NAME==bd_4608_slot_0_ar_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_4/bd_4608_slot_0_r_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_slot_0_r_0 || ORIG_REF_NAME==bd_4608_slot_0_r_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_5/bd_4608_axis_dbg_stub_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_dbg_stub_0 || ORIG_REF_NAME==bd_4608_axis_dbg_stub_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_6/bd_4608_xlconstant_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_xlconstant_0 || ORIG_REF_NAME==bd_4608_xlconstant_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_7/bd_4608_axis_ila_intf_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_ila_intf_0 || ORIG_REF_NAME==bd_4608_axis_ila_intf_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_8/bd_4608_axis_cap_ctrl_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_cap_ctrl_0 || ORIG_REF_NAME==bd_4608_axis_cap_ctrl_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_9/bd_4608_axis_mu0_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu0_0_0 || ORIG_REF_NAME==bd_4608_axis_mu0_0_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_10/bd_4608_axis_mu1_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu1_0_0 || ORIG_REF_NAME==bd_4608_axis_mu1_0_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_11/bd_4608_axis_mu2_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu2_0_0 || ORIG_REF_NAME==bd_4608_axis_mu2_0_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_12/bd_4608_axis_mu3_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu3_0_0 || ORIG_REF_NAME==bd_4608_axis_mu3_0_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_13/bd_4608_axis_mu4_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu4_0_0 || ORIG_REF_NAME==bd_4608_axis_mu4_0_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_14/bd_4608_axis_mu5_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu5_0_0 || ORIG_REF_NAME==bd_4608_axis_mu5_0_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_15/bd_4608_axis_mu6_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu6_0_0 || ORIG_REF_NAME==bd_4608_axis_mu6_0_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_16/bd_4608_axis_mu7_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu7_0_0 || ORIG_REF_NAME==bd_4608_axis_mu7_0_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_17/bd_4608_axis_mu8_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu8_0_0 || ORIG_REF_NAME==bd_4608_axis_mu8_0_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_18/bd_4608_axis_mu9_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu9_0_0 || ORIG_REF_NAME==bd_4608_axis_mu9_0_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_19/bd_4608_axis_mu10_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu10_0_0 || ORIG_REF_NAME==bd_4608_axis_mu10_0_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_20/bd_4608_axis_mu11_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu11_0_0 || ORIG_REF_NAME==bd_4608_axis_mu11_0_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_21/bd_4608_axis_mu12_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu12_0_0 || ORIG_REF_NAME==bd_4608_axis_mu12_0_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_22/bd_4608_axis_mu13_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu13_0_0 || ORIG_REF_NAME==bd_4608_axis_mu13_0_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_23/bd_4608_axis_mu14_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu14_0_0 || ORIG_REF_NAME==bd_4608_axis_mu14_0_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_24/bd_4608_axis_mu15_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu15_0_0 || ORIG_REF_NAME==bd_4608_axis_mu15_0_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_25/bd_4608_axis_mu16_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu16_0_0 || ORIG_REF_NAME==bd_4608_axis_mu16_0_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_26/bd_4608_axis_mu17_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu17_0_0 || ORIG_REF_NAME==bd_4608_axis_mu17_0_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_27/bd_4608_axis_mu18_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu18_0_0 || ORIG_REF_NAME==bd_4608_axis_mu18_0_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_28/bd_4608_axis_mu19_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu19_0_0 || ORIG_REF_NAME==bd_4608_axis_mu19_0_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_29/bd_4608_axis_mu20_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu20_0_0 || ORIG_REF_NAME==bd_4608_axis_mu20_0_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_30/bd_4608_axis_mu21_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu21_0_0 || ORIG_REF_NAME==bd_4608_axis_mu21_0_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_31/bd_4608_axis_mu22_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu22_0_0 || ORIG_REF_NAME==bd_4608_axis_mu22_0_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_32/bd_4608_axis_mu23_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu23_0_0 || ORIG_REF_NAME==bd_4608_axis_mu23_0_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_33/bd_4608_axis_mu24_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu24_0_0 || ORIG_REF_NAME==bd_4608_axis_mu24_0_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_34/bd_4608_axis_mu25_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu25_0_0 || ORIG_REF_NAME==bd_4608_axis_mu25_0_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_35/bd_4608_axis_mu26_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu26_0_0 || ORIG_REF_NAME==bd_4608_axis_mu26_0_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_36/bd_4608_axis_mu27_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu27_0_0 || ORIG_REF_NAME==bd_4608_axis_mu27_0_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_37/bd_4608_axis_mu28_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu28_0_0 || ORIG_REF_NAME==bd_4608_axis_mu28_0_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_38/bd_4608_axis_mu29_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu29_0_0 || ORIG_REF_NAME==bd_4608_axis_mu29_0_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_39/bd_4608_axis_mu30_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu30_0_0 || ORIG_REF_NAME==bd_4608_axis_mu30_0_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_40/bd_4608_axis_mu31_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu31_0_0 || ORIG_REF_NAME==bd_4608_axis_mu31_0_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_41/bd_4608_axis_mu32_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu32_0_0 || ORIG_REF_NAME==bd_4608_axis_mu32_0_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_42/bd_4608_axis_mu33_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu33_0_0 || ORIG_REF_NAME==bd_4608_axis_mu33_0_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_43/bd_4608_axis_mu34_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu34_0_0 || ORIG_REF_NAME==bd_4608_axis_mu34_0_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_44/bd_4608_axis_mu35_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu35_0_0 || ORIG_REF_NAME==bd_4608_axis_mu35_0_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_45/bd_4608_axis_mu36_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu36_0_0 || ORIG_REF_NAME==bd_4608_axis_mu36_0_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_46/bd_4608_axis_dbg_sync_2_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_dbg_sync_2_0 || ORIG_REF_NAME==bd_4608_axis_dbg_sync_2_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_47/bd_4608_axis_dbg_sync_3_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_dbg_sync_3_0 || ORIG_REF_NAME==bd_4608_axis_dbg_sync_3_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_48/bd_4608_axis_dbg_sync_4_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_dbg_sync_4_0 || ORIG_REF_NAME==bd_4608_axis_dbg_sync_4_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_49/bd_4608_axis_dbg_sync_5_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_dbg_sync_5_0 || ORIG_REF_NAME==bd_4608_axis_dbg_sync_5_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_50/bd_4608_axis_dbg_sync_6_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_dbg_sync_6_0 || ORIG_REF_NAME==bd_4608_axis_dbg_sync_6_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_51/bd_4608_tc_axis_mu0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_tc_axis_mu0_0 || ORIG_REF_NAME==bd_4608_tc_axis_mu0_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_52/bd_4608_cc_axis_mu0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_cc_axis_mu0_0 || ORIG_REF_NAME==bd_4608_cc_axis_mu0_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_53/bd_4608_cc_axis_mu1_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_cc_axis_mu1_0 || ORIG_REF_NAME==bd_4608_cc_axis_mu1_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_54/bd_4608_cc_axis_mu2_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_cc_axis_mu2_0 || ORIG_REF_NAME==bd_4608_cc_axis_mu2_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_55/bd_4608_cc_axis_mu3_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_cc_axis_mu3_0 || ORIG_REF_NAME==bd_4608_cc_axis_mu3_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_56/bd_4608_axis_itct_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_itct_0 || ORIG_REF_NAME==bd_4608_axis_itct_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_57/bd_4608_axis_ila_pp_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_ila_pp_0 || ORIG_REF_NAME==bd_4608_axis_ila_pp_0} -quiet] -quiet

# IP: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_58/bd_4608_axis_mem_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4608_axis_mem_0 || ORIG_REF_NAME==bd_4608_axis_mem_0} -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_9/axis_mu_v1_0/constraints/axis_mu_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu0_0_0 || ORIG_REF_NAME==bd_4608_axis_mu0_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_10/axis_mu_v1_0/constraints/axis_mu_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu1_0_0 || ORIG_REF_NAME==bd_4608_axis_mu1_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_11/axis_mu_v1_0/constraints/axis_mu_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu2_0_0 || ORIG_REF_NAME==bd_4608_axis_mu2_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_12/axis_mu_v1_0/constraints/axis_mu_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu3_0_0 || ORIG_REF_NAME==bd_4608_axis_mu3_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_13/axis_mu_v1_0/constraints/axis_mu_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu4_0_0 || ORIG_REF_NAME==bd_4608_axis_mu4_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_14/axis_mu_v1_0/constraints/axis_mu_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu5_0_0 || ORIG_REF_NAME==bd_4608_axis_mu5_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_15/axis_mu_v1_0/constraints/axis_mu_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu6_0_0 || ORIG_REF_NAME==bd_4608_axis_mu6_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_16/axis_mu_v1_0/constraints/axis_mu_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu7_0_0 || ORIG_REF_NAME==bd_4608_axis_mu7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_17/axis_mu_v1_0/constraints/axis_mu_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu8_0_0 || ORIG_REF_NAME==bd_4608_axis_mu8_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_18/axis_mu_v1_0/constraints/axis_mu_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu9_0_0 || ORIG_REF_NAME==bd_4608_axis_mu9_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_19/axis_mu_v1_0/constraints/axis_mu_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu10_0_0 || ORIG_REF_NAME==bd_4608_axis_mu10_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_20/axis_mu_v1_0/constraints/axis_mu_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu11_0_0 || ORIG_REF_NAME==bd_4608_axis_mu11_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_21/axis_mu_v1_0/constraints/axis_mu_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu12_0_0 || ORIG_REF_NAME==bd_4608_axis_mu12_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_22/axis_mu_v1_0/constraints/axis_mu_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu13_0_0 || ORIG_REF_NAME==bd_4608_axis_mu13_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_23/axis_mu_v1_0/constraints/axis_mu_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu14_0_0 || ORIG_REF_NAME==bd_4608_axis_mu14_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_24/axis_mu_v1_0/constraints/axis_mu_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu15_0_0 || ORIG_REF_NAME==bd_4608_axis_mu15_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_25/axis_mu_v1_0/constraints/axis_mu_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu16_0_0 || ORIG_REF_NAME==bd_4608_axis_mu16_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_26/axis_mu_v1_0/constraints/axis_mu_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu17_0_0 || ORIG_REF_NAME==bd_4608_axis_mu17_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_27/axis_mu_v1_0/constraints/axis_mu_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu18_0_0 || ORIG_REF_NAME==bd_4608_axis_mu18_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_28/axis_mu_v1_0/constraints/axis_mu_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu19_0_0 || ORIG_REF_NAME==bd_4608_axis_mu19_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_29/axis_mu_v1_0/constraints/axis_mu_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu20_0_0 || ORIG_REF_NAME==bd_4608_axis_mu20_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_30/axis_mu_v1_0/constraints/axis_mu_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu21_0_0 || ORIG_REF_NAME==bd_4608_axis_mu21_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_31/axis_mu_v1_0/constraints/axis_mu_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu22_0_0 || ORIG_REF_NAME==bd_4608_axis_mu22_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_32/axis_mu_v1_0/constraints/axis_mu_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu23_0_0 || ORIG_REF_NAME==bd_4608_axis_mu23_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_33/axis_mu_v1_0/constraints/axis_mu_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu24_0_0 || ORIG_REF_NAME==bd_4608_axis_mu24_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_34/axis_mu_v1_0/constraints/axis_mu_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu25_0_0 || ORIG_REF_NAME==bd_4608_axis_mu25_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_35/axis_mu_v1_0/constraints/axis_mu_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu26_0_0 || ORIG_REF_NAME==bd_4608_axis_mu26_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_36/axis_mu_v1_0/constraints/axis_mu_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu27_0_0 || ORIG_REF_NAME==bd_4608_axis_mu27_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_37/axis_mu_v1_0/constraints/axis_mu_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu28_0_0 || ORIG_REF_NAME==bd_4608_axis_mu28_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_38/axis_mu_v1_0/constraints/axis_mu_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu29_0_0 || ORIG_REF_NAME==bd_4608_axis_mu29_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_39/axis_mu_v1_0/constraints/axis_mu_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu30_0_0 || ORIG_REF_NAME==bd_4608_axis_mu30_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_40/axis_mu_v1_0/constraints/axis_mu_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu31_0_0 || ORIG_REF_NAME==bd_4608_axis_mu31_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_41/axis_mu_v1_0/constraints/axis_mu_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu32_0_0 || ORIG_REF_NAME==bd_4608_axis_mu32_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_42/axis_mu_v1_0/constraints/axis_mu_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu33_0_0 || ORIG_REF_NAME==bd_4608_axis_mu33_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_43/axis_mu_v1_0/constraints/axis_mu_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu34_0_0 || ORIG_REF_NAME==bd_4608_axis_mu34_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_44/axis_mu_v1_0/constraints/axis_mu_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu35_0_0 || ORIG_REF_NAME==bd_4608_axis_mu35_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_45/axis_mu_v1_0/constraints/axis_mu_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_4608_axis_mu36_0_0 || ORIG_REF_NAME==bd_4608_axis_mu36_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_51/axis_mu_v1_0/constraints/axis_mu_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_4608_tc_axis_mu0_0 || ORIG_REF_NAME==bd_4608_tc_axis_mu0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_52/axis_mu_v1_0/constraints/axis_mu_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_4608_cc_axis_mu0_0 || ORIG_REF_NAME==bd_4608_cc_axis_mu0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_53/axis_mu_v1_0/constraints/axis_mu_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_4608_cc_axis_mu1_0 || ORIG_REF_NAME==bd_4608_cc_axis_mu1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_54/axis_mu_v1_0/constraints/axis_mu_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_4608_cc_axis_mu2_0 || ORIG_REF_NAME==bd_4608_cc_axis_mu2_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_55/axis_mu_v1_0/constraints/axis_mu_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_4608_cc_axis_mu3_0 || ORIG_REF_NAME==bd_4608_cc_axis_mu3_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/bd_4608_ooc.xdc

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/axis_ila_v1_3/constraints/axis_ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_axis_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/axis_ila_v1_3/constraints/axis_ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_axis_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/design_2_axis_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_axis_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
