set_property SRC_FILE_INFO {cfile:/home/younas/Documents/Vivado/hbm_module_2_synth_impl/hbm_module_2_synth_impl.gen/sources_1/bd/design_1/ip/design_1_noc_sim_trig_0/hdl/par/design_1_noc_sim_trig_0_ip.xdc rfile:../../../../../hbm_module_2_synth_impl.gen/sources_1/bd/design_1/ip/design_1_noc_sim_trig_0/hdl/par/design_1_noc_sim_trig_0_ip.xdc id:1 order:EARLY scoped_inst:inst} [current_design]
set_property SRC_FILE_INFO {cfile:/home/younas/Documents/Vivado/hbm_module_2_synth_impl/hbm_module_2_synth_impl.runs/design_1_noc_sim_trig_0_synth_1/dont_touch.xdc rfile:../../../dont_touch.xdc id:2} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -to [get_pins {inst/sim_trig_inst/u_synchronizer_1/SYNC[0].sync_reg_reg[0]/D}]
set_property src_info {type:SCOPED_XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -to [get_pins {inst/sim_trig_inst/u_synchronizer_1/SYNC[1].sync_reg_reg[0]/D}]
set_property src_info {type:SCOPED_XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -to [get_pins {inst/sim_trig_inst/u_synchronizer_1/SYNC[2].sync_reg_reg[0]/D}]
set_property src_info {type:SCOPED_XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -to [get_pins {inst/sim_trig_inst/u_synchronizer_1/SYNC[3].sync_reg_reg[0]/D}]
set_property src_info {type:XDC file:2 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells inst]
