#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2024.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu May 01 09:54:57 PKT 2025
# SW Build 5239630 on Fri Nov 08 22:34:34 MST 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim design_1_wrapper_sim_wrapper_behav -key {Behavioral:sim_1:Functional:design_1_wrapper_sim_wrapper} -tclbatch design_1_wrapper_sim_wrapper.tcl -protoinst "protoinst_files/bd_8be5.protoinst" -protoinst "protoinst_files/design_1.protoinst" -protoinst "protoinst_files/xlnoc.protoinst" -view /home/younas/Documents/Vivado/hbm_module_1/design_1_NoC_Module1_wrapper_sim_wrapper_behav.wcfg -log simulate.log"
xsim design_1_wrapper_sim_wrapper_behav -key {Behavioral:sim_1:Functional:design_1_wrapper_sim_wrapper} -tclbatch design_1_wrapper_sim_wrapper.tcl -protoinst "protoinst_files/bd_8be5.protoinst" -protoinst "protoinst_files/design_1.protoinst" -protoinst "protoinst_files/xlnoc.protoinst" -view /home/younas/Documents/Vivado/hbm_module_1/design_1_NoC_Module1_wrapper_sim_wrapper_behav.wcfg -log simulate.log

