# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.runs/synth_1/design_2_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param bd.open.in_stealth_mode 1
set_param chipscope.flow 0
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xcvh1582-vsva3697-2MP-e-S

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.cache/wt [current_project]
set_property parent.project_path /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/hdl/design_2_wrapper.v
add_files /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.srcs/sources_1/bd/design_2/design_2.bd
set_property used_in_implementation false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axi_noc_0_0/bd_0/ip/ip_0/xdc/bd_48e0_HBM03_AXI_nmu_0.xdc]
set_property used_in_implementation false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axi_noc_0_0/bd_0/ip/ip_2/xdc/bd_48e0_HBM02_AXI_nmu_0.xdc]
set_property used_in_implementation false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axi_noc_0_0/bd_0/ip/ip_3/xdc/bd_48e0_HBM01_AXI_nmu_0.xdc]
set_property used_in_implementation false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axi_noc_0_0/bd_0/ip/ip_4/xdc/bd_48e0_HBM00_AXI_nmu_0.xdc]
set_property used_in_implementation false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axi_noc_0_0/bd_0/ip/ip_5/hdl/par/bd_48e0_MC_hbmc_0_ip.xdc]
set_property used_in_implementation false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axi_noc_0_0/design_2_axi_noc_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axi_noc_0_0/design_2_axi_noc_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axi_noc_0_0/design_2_axi_noc_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_noc_tg_0/ip_1/design_2_noc_tg_0_axi_register_slice_wronly_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_noc_tg_0/ip_0/design_2_noc_tg_0_axi4_register_slice_clocks.xdc]
set_property used_in_synthesis false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_noc_tg_0/hdl/par/design_2_noc_tg_0_ip.xdc]
set_property used_in_implementation false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_noc_tg_0/hdl/par/design_2_noc_tg_0_ip.xdc]
set_property used_in_implementation false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_noc_tg_0/par/design_2_noc_tg_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_noc_sim_trig_0/ip_0/axi_apb_bridge_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_noc_sim_trig_0/hdl/par/design_2_noc_sim_trig_0_ip.xdc]
set_property used_in_implementation false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_noc_tg_pmon_0/hdl/par/design_2_noc_tg_pmon_0_ip.xdc]
set_property used_in_implementation false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_noc_tg_1_0/ip_1/design_2_noc_tg_1_0_axi_register_slice_wronly_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_noc_tg_1_0/ip_0/design_2_noc_tg_1_0_axi4_register_slice_clocks.xdc]
set_property used_in_synthesis false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_noc_tg_1_0/hdl/par/design_2_noc_tg_1_0_ip.xdc]
set_property used_in_implementation false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_noc_tg_1_0/hdl/par/design_2_noc_tg_1_0_ip.xdc]
set_property used_in_implementation false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_noc_tg_1_0/par/design_2_noc_tg_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_noc_tg_pmon_1_0/hdl/par/design_2_noc_tg_pmon_1_0_ip.xdc]
set_property used_in_implementation false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_noc_tg_2_0/ip_1/design_2_noc_tg_2_0_axi_register_slice_wronly_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_noc_tg_2_0/ip_0/design_2_noc_tg_2_0_axi4_register_slice_clocks.xdc]
set_property used_in_synthesis false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_noc_tg_2_0/hdl/par/design_2_noc_tg_2_0_ip.xdc]
set_property used_in_implementation false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_noc_tg_2_0/hdl/par/design_2_noc_tg_2_0_ip.xdc]
set_property used_in_implementation false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_noc_tg_2_0/par/design_2_noc_tg_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_noc_tg_pmon_2_0/hdl/par/design_2_noc_tg_pmon_2_0_ip.xdc]
set_property used_in_implementation false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_noc_tg_3_0/ip_1/design_2_noc_tg_3_0_axi_register_slice_wronly_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_noc_tg_3_0/ip_0/design_2_noc_tg_3_0_axi4_register_slice_clocks.xdc]
set_property used_in_synthesis false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_noc_tg_3_0/hdl/par/design_2_noc_tg_3_0_ip.xdc]
set_property used_in_implementation false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_noc_tg_3_0/hdl/par/design_2_noc_tg_3_0_ip.xdc]
set_property used_in_implementation false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_noc_tg_3_0/par/design_2_noc_tg_3_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_noc_tg_pmon_3_0/hdl/par/design_2_noc_tg_pmon_3_0_ip.xdc]
set_property used_in_implementation false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_versal_cips_0_0/bd_0/ip/ip_0/bd_802a_pspmc_0_0.xdc]
set_property used_in_synthesis false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_versal_cips_0_0/bd_0/ip/ip_0/pspmc_v1_4/constraints/usr_constraints.xdc]
set_property used_in_implementation false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_versal_cips_0_0/bd_0/ip/ip_0/pspmc_v1_4/constraints/usr_constraints.xdc]
set_property used_in_implementation false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_versal_cips_0_0/bd_0/bd_802a_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_proc_sys_reset_0_0/design_2_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_proc_sys_reset_0_0/design_2_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_proc_sys_reset_0_0/design_2_proc_sys_reset_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_clk_wizard_0_0/design_2_clk_wizard_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_clk_wizard_0_0/design_2_clk_wizard_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_clk_wizard_0_0/design_2_clk_wizard_0_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_9/axis_mu_v1_0/constraints/axis_mu_impl.xdc]
set_property used_in_implementation false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_9/axis_mu_v1_0/constraints/axis_mu_impl.xdc]
set_property used_in_synthesis false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_10/axis_mu_v1_0/constraints/axis_mu_impl.xdc]
set_property used_in_implementation false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_10/axis_mu_v1_0/constraints/axis_mu_impl.xdc]
set_property used_in_synthesis false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_11/axis_mu_v1_0/constraints/axis_mu_impl.xdc]
set_property used_in_implementation false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_11/axis_mu_v1_0/constraints/axis_mu_impl.xdc]
set_property used_in_synthesis false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_12/axis_mu_v1_0/constraints/axis_mu_impl.xdc]
set_property used_in_implementation false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_12/axis_mu_v1_0/constraints/axis_mu_impl.xdc]
set_property used_in_synthesis false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_13/axis_mu_v1_0/constraints/axis_mu_impl.xdc]
set_property used_in_implementation false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_13/axis_mu_v1_0/constraints/axis_mu_impl.xdc]
set_property used_in_synthesis false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_14/axis_mu_v1_0/constraints/axis_mu_impl.xdc]
set_property used_in_implementation false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_14/axis_mu_v1_0/constraints/axis_mu_impl.xdc]
set_property used_in_synthesis false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_15/axis_mu_v1_0/constraints/axis_mu_impl.xdc]
set_property used_in_implementation false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_15/axis_mu_v1_0/constraints/axis_mu_impl.xdc]
set_property used_in_synthesis false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_16/axis_mu_v1_0/constraints/axis_mu_impl.xdc]
set_property used_in_implementation false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_16/axis_mu_v1_0/constraints/axis_mu_impl.xdc]
set_property used_in_synthesis false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_17/axis_mu_v1_0/constraints/axis_mu_impl.xdc]
set_property used_in_implementation false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_17/axis_mu_v1_0/constraints/axis_mu_impl.xdc]
set_property used_in_synthesis false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_18/axis_mu_v1_0/constraints/axis_mu_impl.xdc]
set_property used_in_implementation false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_18/axis_mu_v1_0/constraints/axis_mu_impl.xdc]
set_property used_in_synthesis false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_19/axis_mu_v1_0/constraints/axis_mu_impl.xdc]
set_property used_in_implementation false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_19/axis_mu_v1_0/constraints/axis_mu_impl.xdc]
set_property used_in_synthesis false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_20/axis_mu_v1_0/constraints/axis_mu_impl.xdc]
set_property used_in_implementation false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_20/axis_mu_v1_0/constraints/axis_mu_impl.xdc]
set_property used_in_synthesis false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_21/axis_mu_v1_0/constraints/axis_mu_impl.xdc]
set_property used_in_implementation false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_21/axis_mu_v1_0/constraints/axis_mu_impl.xdc]
set_property used_in_synthesis false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_22/axis_mu_v1_0/constraints/axis_mu_impl.xdc]
set_property used_in_implementation false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_22/axis_mu_v1_0/constraints/axis_mu_impl.xdc]
set_property used_in_synthesis false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_23/axis_mu_v1_0/constraints/axis_mu_impl.xdc]
set_property used_in_implementation false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_23/axis_mu_v1_0/constraints/axis_mu_impl.xdc]
set_property used_in_synthesis false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_24/axis_mu_v1_0/constraints/axis_mu_impl.xdc]
set_property used_in_implementation false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_24/axis_mu_v1_0/constraints/axis_mu_impl.xdc]
set_property used_in_synthesis false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_25/axis_mu_v1_0/constraints/axis_mu_impl.xdc]
set_property used_in_implementation false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_25/axis_mu_v1_0/constraints/axis_mu_impl.xdc]
set_property used_in_synthesis false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_26/axis_mu_v1_0/constraints/axis_mu_impl.xdc]
set_property used_in_implementation false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_26/axis_mu_v1_0/constraints/axis_mu_impl.xdc]
set_property used_in_synthesis false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_27/axis_mu_v1_0/constraints/axis_mu_impl.xdc]
set_property used_in_implementation false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_27/axis_mu_v1_0/constraints/axis_mu_impl.xdc]
set_property used_in_synthesis false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_28/axis_mu_v1_0/constraints/axis_mu_impl.xdc]
set_property used_in_implementation false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_28/axis_mu_v1_0/constraints/axis_mu_impl.xdc]
set_property used_in_synthesis false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_29/axis_mu_v1_0/constraints/axis_mu_impl.xdc]
set_property used_in_implementation false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_29/axis_mu_v1_0/constraints/axis_mu_impl.xdc]
set_property used_in_synthesis false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_30/axis_mu_v1_0/constraints/axis_mu_impl.xdc]
set_property used_in_implementation false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_30/axis_mu_v1_0/constraints/axis_mu_impl.xdc]
set_property used_in_synthesis false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_31/axis_mu_v1_0/constraints/axis_mu_impl.xdc]
set_property used_in_implementation false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_31/axis_mu_v1_0/constraints/axis_mu_impl.xdc]
set_property used_in_synthesis false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_32/axis_mu_v1_0/constraints/axis_mu_impl.xdc]
set_property used_in_implementation false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_32/axis_mu_v1_0/constraints/axis_mu_impl.xdc]
set_property used_in_synthesis false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_33/axis_mu_v1_0/constraints/axis_mu_impl.xdc]
set_property used_in_implementation false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_33/axis_mu_v1_0/constraints/axis_mu_impl.xdc]
set_property used_in_synthesis false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_34/axis_mu_v1_0/constraints/axis_mu_impl.xdc]
set_property used_in_implementation false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_34/axis_mu_v1_0/constraints/axis_mu_impl.xdc]
set_property used_in_synthesis false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_35/axis_mu_v1_0/constraints/axis_mu_impl.xdc]
set_property used_in_implementation false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_35/axis_mu_v1_0/constraints/axis_mu_impl.xdc]
set_property used_in_synthesis false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_36/axis_mu_v1_0/constraints/axis_mu_impl.xdc]
set_property used_in_implementation false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_36/axis_mu_v1_0/constraints/axis_mu_impl.xdc]
set_property used_in_synthesis false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_37/axis_mu_v1_0/constraints/axis_mu_impl.xdc]
set_property used_in_implementation false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_37/axis_mu_v1_0/constraints/axis_mu_impl.xdc]
set_property used_in_synthesis false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_38/axis_mu_v1_0/constraints/axis_mu_impl.xdc]
set_property used_in_implementation false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_38/axis_mu_v1_0/constraints/axis_mu_impl.xdc]
set_property used_in_synthesis false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_39/axis_mu_v1_0/constraints/axis_mu_impl.xdc]
set_property used_in_implementation false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_39/axis_mu_v1_0/constraints/axis_mu_impl.xdc]
set_property used_in_synthesis false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_40/axis_mu_v1_0/constraints/axis_mu_impl.xdc]
set_property used_in_implementation false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_40/axis_mu_v1_0/constraints/axis_mu_impl.xdc]
set_property used_in_synthesis false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_41/axis_mu_v1_0/constraints/axis_mu_impl.xdc]
set_property used_in_implementation false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_41/axis_mu_v1_0/constraints/axis_mu_impl.xdc]
set_property used_in_synthesis false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_42/axis_mu_v1_0/constraints/axis_mu_impl.xdc]
set_property used_in_implementation false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_42/axis_mu_v1_0/constraints/axis_mu_impl.xdc]
set_property used_in_synthesis false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_43/axis_mu_v1_0/constraints/axis_mu_impl.xdc]
set_property used_in_implementation false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_43/axis_mu_v1_0/constraints/axis_mu_impl.xdc]
set_property used_in_synthesis false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_44/axis_mu_v1_0/constraints/axis_mu_impl.xdc]
set_property used_in_implementation false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_44/axis_mu_v1_0/constraints/axis_mu_impl.xdc]
set_property used_in_synthesis false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_45/axis_mu_v1_0/constraints/axis_mu_impl.xdc]
set_property used_in_implementation false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_45/axis_mu_v1_0/constraints/axis_mu_impl.xdc]
set_property used_in_synthesis false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_51/axis_mu_v1_0/constraints/axis_mu_impl.xdc]
set_property used_in_implementation false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_51/axis_mu_v1_0/constraints/axis_mu_impl.xdc]
set_property used_in_synthesis false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_52/axis_mu_v1_0/constraints/axis_mu_impl.xdc]
set_property used_in_implementation false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_52/axis_mu_v1_0/constraints/axis_mu_impl.xdc]
set_property used_in_synthesis false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_53/axis_mu_v1_0/constraints/axis_mu_impl.xdc]
set_property used_in_implementation false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_53/axis_mu_v1_0/constraints/axis_mu_impl.xdc]
set_property used_in_synthesis false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_54/axis_mu_v1_0/constraints/axis_mu_impl.xdc]
set_property used_in_implementation false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_54/axis_mu_v1_0/constraints/axis_mu_impl.xdc]
set_property used_in_synthesis false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_55/axis_mu_v1_0/constraints/axis_mu_impl.xdc]
set_property used_in_implementation false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/ip/ip_55/axis_mu_v1_0/constraints/axis_mu_impl.xdc]
set_property used_in_implementation false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/bd_0/bd_4608_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/axis_ila_v1_3/constraints/axis_ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/axis_ila_v1_3/constraints/axis_ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/axis_ila_v1_3/constraints/axis_ila.xdc]
set_property used_in_implementation false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/ip/design_2_axis_ila_0_0/design_2_axis_ila_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/design_2_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/nsln/design_2.nts]
set_property used_in_implementation false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/nsln/design_2.nts]
set_property used_in_synthesis false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/nsln/design_2.ncr]
set_property used_in_implementation false [get_files -all /home/younas/Documents/Vivado/hbm_module_2/hbm_module_2.gen/sources_1/bd/design_2/nsln/design_2.ncr]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top design_2_wrapper -part xcvh1582-vsva3697-2MP-e-S
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef design_2_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file design_2_wrapper_utilization_synth.rpt -pb design_2_wrapper_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
