#!/usr/bin/env bash
#**********************************************************************************************************
# Vivado (TM) v2024.2 (64-bit)
#
# Script generated by Vivado on Wed Apr 30 18:52:31 PKT 2025
# SW Build 5239630 on Fri Nov 08 22:34:34 MST 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved. 
#
# Filename     : design_1.sh
# Simulator    : Cadence Xcelium Parallel Simulator
# Description  : Simulation script generated by export_simulation Tcl command
# Purpose      : Run 'compile', 'elaborate', 'simulate' steps for compiling, elaborating and simulating the
#                design. The script will copy the library mapping file from the compiled library directory,
#                create design library directories and library mappings in the mapping file.
#
# Usage        : design_1.sh
#                design_1.sh [-lib_map_path] [-step] [-keep_index] [-noclean_files]*
#                design_1.sh [-reset_run]
#                design_1.sh [-reset_log]
#                design_1.sh [-help]
#
#               * The -noclean_files switch is deprecated and will not peform any function (by default, the
#                 simulator generated files will not be removed unless -reset_run switch is used)
#
# Prerequisite : Before running export_simulation, you must first compile the AMD simulation library
#                using the 'compile_simlib' Tcl command (for more information, run 'compile_simlib -help'
#                command in the Vivado Tcl shell). After compiling the library, specify the -lib_map_path
#                switch with the directory path where the library is created while generating the script
#                with export_simulation.
#
#                Alternatively, you can set the library path by setting the following project property:-
#
#                 set_property compxlib.<simulator>_compiled_library_dir <path> [current_project]
#
#                You can also point to the simulation library by either setting the 'lib_map_path' global
#                variable in this script or specify it with the '-lib_map_path' switch while executing this
#                script (type 'design_1.sh -help' for more information).
#
#                Note: For pure RTL based designs, the -lib_map_path switch can be specified later with the
#                generated script, but if design is targetted for system simulation containing SystemC/C++/C
#                sources, then the library path MUST be specified upfront when calling export_simulation.
#
#                For more information, refer 'Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#**********************************************************************************************************

# catch pipeline exit status
set -Eeuo pipefail

# set xmvhdl compile options
xmvhdl_opts="-64bit -messages -relax -logfile .tmp_log -update"

# set xmvlog compile options
xmvlog_opts="-64bit -messages -logfile .tmp_log -update"

# set xmelab elaboration options
xmelab_opts="-64bit -relax -access +r -namemap_mixgen -messages -logfile elaborate.log"

# set xmsim simulation options
xmsim_opts="-64bit -logfile simulate.log"

# set design libraries for elaboration
design_libs_elab="-libname xilinx_vip -libname xpm -libname noc_nmu_sim_v1_0_0 -libname noc_hbm_nmu_sim_v1_0_0 -libname xil_defaultlib -libname xlconstant_v1_1_9 -libname noc_hbm_v1_0_1 -libname clk_gen_sim_v1_0_4 -libname axi_infrastructure_v1_1_0 -libname axi_register_slice_v2_1_33 -libname axis_dbg_stub_v1_0_1 -libname axis_dbg_sync_v1_0_1 -libname axis_vio_v1_0_12 -libname axi_vip_v1_1_19 -libname axis_infrastructure_v1_1_1 -libname axi4stream_vip_v1_1_19 -libname perf_axi_tg_v1_0_15 -libname lib_pkg_v1_0_4 -libname axi_apb_bridge_v3_0_20 -libname sim_trig_v1_0_13 -libname axi_pmon_v1_0_2 -libname lib_cdc_v1_0_3 -libname proc_sys_reset_v5_0_16 -libname xilinx_vip -libname unisims_ver -libname unimacro_ver -libname secureip"

# set design libraries
design_libs=(simprims_ver xilinx_vip xpm noc_nmu_sim_v1_0_0 noc_hbm_nmu_sim_v1_0_0 xil_defaultlib xlconstant_v1_1_9 noc_hbm_v1_0_1 clk_gen_sim_v1_0_4 axi_infrastructure_v1_1_0 axi_register_slice_v2_1_33 axis_dbg_stub_v1_0_1 axis_dbg_sync_v1_0_1 axis_vio_v1_0_12 axi_vip_v1_1_19 axis_infrastructure_v1_1_1 axi4stream_vip_v1_1_19 perf_axi_tg_v1_0_15 lib_pkg_v1_0_4 axi_apb_bridge_v3_0_20 sim_trig_v1_0_13 axi_pmon_v1_0_2 lib_cdc_v1_0_3 proc_sys_reset_v5_0_16)

# simulation root library directory
sim_lib_dir="xcelium_lib"

# script info
echo -e "design_1.sh - Script generated by export_simulation (Vivado v2024.2 (64-bit)-id)\n"

# main steps
run()
{
  check_args $*
  setup
  if [[ ($b_step == 1) ]]; then
    case $step in
      "compile" )
       init_lib
       compile
      ;;
      "elaborate" )
       elaborate
      ;;
      "simulate" )
       simulate
      ;;
      * )
        echo -e "ERROR: Invalid or missing step '$step' (type \"./design_1.sh -help\" for more information)\n"
        exit 1
      esac
  else
    init_lib
    compile
    elaborate
    simulate
  fi
}

# RUN_STEP: <compile>
compile()
{
  xmvlog -work xilinx_vip $xmvlog_opts -sv +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/6436/hdl/bfm" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/01b2/hdl/bfm_hbm" +incdir+"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/interfaces" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/PHY_IO_PLL" +incdir+"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/2997/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/bfm" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/4506/hdl" +incdir+"/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
  "/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
  "/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
  "/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
  "/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
  "/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
  "/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
  "/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
  "/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee compile.log; cat .tmp_log > xmvlog.log 2>/dev/null

  xmvlog -work xpm $xmvlog_opts -sv +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/6436/hdl/bfm" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/01b2/hdl/bfm_hbm" +incdir+"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/interfaces" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/PHY_IO_PLL" +incdir+"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/2997/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/bfm" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/4506/hdl" +incdir+"/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "/tools/Xilinx/Vivado/2024.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
  "/tools/Xilinx/Vivado/2024.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
  "/tools/Xilinx/Vivado/2024.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work xpm -V93 $xmvhdl_opts \
  "/tools/Xilinx/Vivado/2024.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log > xmvhdl.log 2>/dev/null

  xmvlog -work noc_nmu_sim_v1_0_0 $xmvlog_opts -sv +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/6436/hdl/bfm" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/01b2/hdl/bfm_hbm" +incdir+"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/interfaces" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/PHY_IO_PLL" +incdir+"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/2997/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/bfm" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/4506/hdl" +incdir+"/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/6436/hdl/noc_nmu_sim_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work noc_hbm_nmu_sim_v1_0_0 $xmvlog_opts -sv +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/6436/hdl/bfm" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/01b2/hdl/bfm_hbm" +incdir+"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/interfaces" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/PHY_IO_PLL" +incdir+"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/2997/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/bfm" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/4506/hdl" +incdir+"/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/01b2/hdl/noc_hbm_nmu_sim_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/6436/hdl/bfm" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/01b2/hdl/bfm_hbm" +incdir+"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/interfaces" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/PHY_IO_PLL" +incdir+"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/2997/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/bfm" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/4506/hdl" +incdir+"/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_0/hdl/bfm/bd_8be5_HBM00_AXI_nmu_0_top.sv" \
  "../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_0/hdl/bfm/bd_8be5_HBM00_AXI_nmu_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xlconstant_v1_1_9 $xmvlog_opts +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/6436/hdl/bfm" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/01b2/hdl/bfm_hbm" +incdir+"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/interfaces" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/PHY_IO_PLL" +incdir+"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/2997/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/bfm" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/4506/hdl" +incdir+"/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/e2d2/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/6436/hdl/bfm" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/01b2/hdl/bfm_hbm" +incdir+"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/interfaces" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/PHY_IO_PLL" +incdir+"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/2997/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/bfm" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/4506/hdl" +incdir+"/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_1/sim/bd_8be5_const_0_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/6436/hdl/bfm" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/01b2/hdl/bfm_hbm" +incdir+"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/interfaces" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/PHY_IO_PLL" +incdir+"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/2997/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/bfm" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/4506/hdl" +incdir+"/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/rtl/bd_8be5_MC_hbmc_0_top_unisim_stack0.sv" \
  "../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/rtl/bd_8be5_MC_hbmc_0_top_wrapper.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work noc_hbm_v1_0_1 $xmvlog_opts -sv +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/6436/hdl/bfm" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/01b2/hdl/bfm_hbm" +incdir+"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/interfaces" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/PHY_IO_PLL" +incdir+"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/2997/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/bfm" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/4506/hdl" +incdir+"/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/Unisims/HBM_CHNL.sv" \
  "../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/Unisims/HBM_CHNL_PHY_ONLY.sv" \
  "../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/BM_HBM_MC.sv" \
  "../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/hbm_dbuf_bfm.sv" \
  "../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/hbm_dc_bfm.sv" \
  "../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/hbm_dpath_bfm.sv" \
  "../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/hbm_refresh_bfm.sv" \
  "../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/hbm_txnq_bfm.sv" \
  "../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/hbm_pend_fifo_bfm.sv" \
  "../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/hbm_farb_bfm.sv" \
  "../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/hbmmc_na_bfm.sv" \
  "../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/lbus_checker.sv" \
  "../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/hbmmc_mc_bfm.sv" \
  "../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/hbm_ctrl_bfm.sv" \
  "../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/hbm_bfm_phy_shim.sv" \
  "../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/PHY_IO_PLL/BM_HBM_IO_CHNL.sv" \
  "../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/PHY_IO_PLL/BM_HBM_PHY_CHNL.sv" \
  "../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/PHY_IO_PLL/BM_HPLL.sv" \
  "../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/PHY_IO_PLL/cmt_hbm_hpll_bfm.sv" \
  "../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/PHY_IO_PLL/hbm_io_chnl_top_bfm.sv" \
  "../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/PHY_IO_PLL/hbm_phy_chnl_8_1_bfm.sv" \
  "../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/PHY_IO_PLL/hbm_phy_chnl_intf_bfm.sv" \
  "../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/PHY_IO_PLL/hbm_phy_chnl_top_bfm.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/6436/hdl/bfm" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/01b2/hdl/bfm_hbm" +incdir+"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/interfaces" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/PHY_IO_PLL" +incdir+"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/2997/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/bfm" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/4506/hdl" +incdir+"/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model/hbm_responder.sv" \
  "../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/bfm/PHY_IO_PLL/BM_HBM_PHY_MS.sv" \
  "../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/bfm/PHY_IO_PLL/BM_IO_MS.sv" \
  "../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/bfm/PHY_IO_PLL/hbm_io_ms_top_bfm.sv" \
  "../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/bfm/PHY_IO_PLL/hbm_phy_ms_top_bfm.sv" \
  "../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/rtl/bd_8be5_MC_hbmc_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/6436/hdl/bfm" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/01b2/hdl/bfm_hbm" +incdir+"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/interfaces" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/PHY_IO_PLL" +incdir+"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/2997/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/bfm" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/4506/hdl" +incdir+"/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/sim/bd_8be5.v" \
  "../../../bd/design_1/ip/design_1_axi_noc_0_0/sim/design_1_axi_noc_0_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work clk_gen_sim_v1_0_4 $xmvlog_opts -sv +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/6436/hdl/bfm" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/01b2/hdl/bfm_hbm" +incdir+"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/interfaces" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/PHY_IO_PLL" +incdir+"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/2997/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/bfm" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/4506/hdl" +incdir+"/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/0c0c/hdl/clk_gen_sim_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/6436/hdl/bfm" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/01b2/hdl/bfm_hbm" +incdir+"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/interfaces" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/PHY_IO_PLL" +incdir+"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/2997/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/bfm" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/4506/hdl" +incdir+"/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_noc_clk_gen_0/hdl/design_1_noc_clk_gen_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_infrastructure_v1_1_0 $xmvlog_opts +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/6436/hdl/bfm" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/01b2/hdl/bfm_hbm" +incdir+"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/interfaces" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/PHY_IO_PLL" +incdir+"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/2997/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/bfm" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/4506/hdl" +incdir+"/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_register_slice_v2_1_33 $xmvlog_opts +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/6436/hdl/bfm" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/01b2/hdl/bfm_hbm" +incdir+"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/interfaces" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/PHY_IO_PLL" +incdir+"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/2997/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/bfm" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/4506/hdl" +incdir+"/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/3ee4/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/6436/hdl/bfm" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/01b2/hdl/bfm_hbm" +incdir+"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/interfaces" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/PHY_IO_PLL" +incdir+"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/2997/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/bfm" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/4506/hdl" +incdir+"/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_noc_tg_0/ip_0/sim/design_1_noc_tg_0_axi4_register_slice.v" \
  "../../../bd/design_1/ip/design_1_noc_tg_0/ip_1/sim/design_1_noc_tg_0_axi_register_slice_wronly.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axis_dbg_stub_v1_0_1 $xmvlog_opts +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/6436/hdl/bfm" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/01b2/hdl/bfm_hbm" +incdir+"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/interfaces" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/PHY_IO_PLL" +incdir+"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/2997/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/bfm" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/4506/hdl" +incdir+"/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b54f/hdl/axis_dbg_stub_v1_0_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axis_dbg_sync_v1_0_1 $xmvlog_opts +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/6436/hdl/bfm" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/01b2/hdl/bfm_hbm" +incdir+"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/interfaces" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/PHY_IO_PLL" +incdir+"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/2997/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/bfm" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/4506/hdl" +incdir+"/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/7899/hdl/axis_dbg_sync_v1_0_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axis_vio_v1_0_12 $xmvlog_opts -sv +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/6436/hdl/bfm" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/01b2/hdl/bfm_hbm" +incdir+"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/interfaces" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/PHY_IO_PLL" +incdir+"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/2997/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/bfm" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/4506/hdl" +incdir+"/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/2997/hdl/axis_vio_v1_0_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/6436/hdl/bfm" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/01b2/hdl/bfm_hbm" +incdir+"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/interfaces" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/PHY_IO_PLL" +incdir+"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/2997/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/bfm" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/4506/hdl" +incdir+"/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_noc_tg_0/ip_2/sim/design_1_noc_tg_0_vio.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/6436/hdl/bfm" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/01b2/hdl/bfm_hbm" +incdir+"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/interfaces" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/PHY_IO_PLL" +incdir+"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/2997/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/bfm" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/4506/hdl" +incdir+"/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_noc_tg_0/ip_3/sim/design_1_noc_tg_0_vip_pkg.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_vip_v1_1_19 $xmvlog_opts -sv +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/6436/hdl/bfm" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/01b2/hdl/bfm_hbm" +incdir+"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/interfaces" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/PHY_IO_PLL" +incdir+"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/2997/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/bfm" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/4506/hdl" +incdir+"/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/8c45/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/6436/hdl/bfm" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/01b2/hdl/bfm_hbm" +incdir+"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/interfaces" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/PHY_IO_PLL" +incdir+"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/2997/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/bfm" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/4506/hdl" +incdir+"/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_noc_tg_0/ip_3/sim/design_1_noc_tg_0_vip.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axis_infrastructure_v1_1_1 $xmvlog_opts +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/6436/hdl/bfm" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/01b2/hdl/bfm_hbm" +incdir+"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/interfaces" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/PHY_IO_PLL" +incdir+"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/2997/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/bfm" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/4506/hdl" +incdir+"/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/434f/hdl/axis_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi4stream_vip_v1_1_19 $xmvlog_opts -sv +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/6436/hdl/bfm" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/01b2/hdl/bfm_hbm" +incdir+"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/interfaces" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/PHY_IO_PLL" +incdir+"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/2997/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/bfm" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/4506/hdl" +incdir+"/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/51ff/hdl/axi4stream_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work perf_axi_tg_v1_0_15 $xmvlog_opts -sv +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/6436/hdl/bfm" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/01b2/hdl/bfm_hbm" +incdir+"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/interfaces" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/PHY_IO_PLL" +incdir+"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/2997/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/bfm" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/4506/hdl" +incdir+"/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/bfm/axi_data_integrity_checker.sv" \
  "../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/bfm/addr_cls_pkg.sv" \
  "../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/bfm/top_axi_mst_ext_if.sv" \
  "../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/bfm/top_axis_mst_ext_if.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/6436/hdl/bfm" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/01b2/hdl/bfm_hbm" +incdir+"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/interfaces" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/PHY_IO_PLL" +incdir+"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/2997/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/bfm" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/4506/hdl" +incdir+"/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_noc_tg_0/hdl/rtl/design_1_noc_tg_0_tg_top.sv" \
  "../../../bd/design_1/ip/design_1_noc_tg_0/hdl/rtl/design_1_noc_tg_0_csvsptg_top.sv" \
  "../../../bd/design_1/ip/design_1_noc_tg_0/hdl/bfm/design_1_noc_tg_0_top.sv" \
  "../../../bd/design_1/ip/design_1_noc_tg_0/hdl/csv_sptg/rtl/tg_rtl/design_1_noc_tg_0_syn_top.sv" \
  "../../../bd/design_1/ip/design_1_noc_tg_0/hdl/bfm/design_1_noc_tg_0_top_axi_mst.sv" \
  "../../../bd/design_1/ip/design_1_noc_tg_0/hdl/rtl/design_1_noc_tg_0_reg_space.sv" \
  "../../../bd/design_1/ip/design_1_noc_tg_0/hdl/rtl/design_1_noc_tg_0_top_axi_stream_sptg.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work perf_axi_tg_v1_0_15 $xmvlog_opts -sv +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/6436/hdl/bfm" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/01b2/hdl/bfm_hbm" +incdir+"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/interfaces" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/PHY_IO_PLL" +incdir+"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/2997/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/bfm" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/4506/hdl" +incdir+"/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl/axi_inst_core.sv" \
  "../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl/axi_rdch_ctrl.sv" \
  "../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl/axi_stream_inst_core.sv" \
  "../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl/axi_stream_sptg.sv" \
  "../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl/axi_wrch_ctrl.sv" \
  "../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl/mem_tg_mode_data_pat_generator.sv" \
  "../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl/axi_rd_wr_err_detect.sv" \
  "../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl/atg_axi_tg_data_prbs.sv" \
  "../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl/atg_axi_tg_prbs_gen.sv" \
  "../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl/atg_axi_tg_data_prbs_seed.sv" \
  "../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl/cfg_reg_rw.sv" \
  "../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl/cnst_id_latency.sv" \
  "../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl/di_check_cnst_id.sv" \
  "../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl/di_check_mult_id.sv" \
  "../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl/incr_id_latency.sv" \
  "../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl/inst_fetch.sv" \
  "../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl/inst_fifo.sv" \
  "../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl/addr_decoder.sv" \
  "../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl/prbs_data_gen.sv" \
  "../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl/prbs_generator_32b.sv" \
  "../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl/reg_space_stream.sv" \
  "../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl/mem_strobe_gen.sv" \
  "../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl/mem_strb_stream_gen.sv" \
  "../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl/trig_in_out_sync.sv" \
  "../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl/sptg_synchronizer.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/6436/hdl/bfm" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/01b2/hdl/bfm_hbm" +incdir+"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/interfaces" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/PHY_IO_PLL" +incdir+"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/2997/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/bfm" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/4506/hdl" +incdir+"/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_noc_tg_0/sim/design_1_noc_tg_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work lib_pkg_v1_0_4 -V93 $xmvhdl_opts \
  "../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/8c68/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work axi_apb_bridge_v3_0_20 -V93 $xmvhdl_opts \
  "../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/8d5f/hdl/axi_apb_bridge_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/design_1/ip/design_1_noc_sim_trig_0/ip_0/sim/axi_apb_bridge_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/6436/hdl/bfm" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/01b2/hdl/bfm_hbm" +incdir+"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/interfaces" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/PHY_IO_PLL" +incdir+"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/2997/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/bfm" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/4506/hdl" +incdir+"/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_noc_sim_trig_0/hdl/design_1_noc_sim_trig_0_top.sv" \
  "../../../bd/design_1/ip/design_1_noc_sim_trig_0/hdl/design_1_noc_sim_trig_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work sim_trig_v1_0_13 $xmvlog_opts -sv +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/6436/hdl/bfm" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/01b2/hdl/bfm_hbm" +incdir+"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/interfaces" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/PHY_IO_PLL" +incdir+"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/2997/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/bfm" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/4506/hdl" +incdir+"/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/9cb8/hdl/sim_trig_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/6436/hdl/bfm" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/01b2/hdl/bfm_hbm" +incdir+"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/interfaces" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/PHY_IO_PLL" +incdir+"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/2997/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/bfm" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/4506/hdl" +incdir+"/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_noc_sim_trig_0/hdl/rtl/traffic_shaping.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_pmon_v1_0_2 $xmvlog_opts -sv +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/6436/hdl/bfm" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/01b2/hdl/bfm_hbm" +incdir+"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/interfaces" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/PHY_IO_PLL" +incdir+"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/2997/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/bfm" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/4506/hdl" +incdir+"/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/3f57/hdl/axi_pmon_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/6436/hdl/bfm" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/01b2/hdl/bfm_hbm" +incdir+"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/interfaces" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/PHY_IO_PLL" +incdir+"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/2997/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/bfm" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/4506/hdl" +incdir+"/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_noc_tg_pmon_0/sim/design_1_noc_tg_pmon_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/6436/hdl/bfm" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/01b2/hdl/bfm_hbm" +incdir+"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/interfaces" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/PHY_IO_PLL" +incdir+"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/2997/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/bfm" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/4506/hdl" +incdir+"/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_clk_wiz_0/design_1_clk_wiz_0_clocking_structure.v" \
  "../../../bd/design_1/ip/design_1_clk_wiz_0/design_1_clk_wiz_0_clocking_MBUFGCE_CE_DLY.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/6436/hdl/bfm" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/01b2/hdl/bfm_hbm" +incdir+"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/interfaces" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/PHY_IO_PLL" +incdir+"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/2997/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/bfm" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/4506/hdl" +incdir+"/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_clk_wiz_0/design_1_clk_wiz_0_clocking_cmt_dpll_fd_cal.sv" \
  "../../../bd/design_1/ip/design_1_clk_wiz_0/design_1_clk_wiz_0_clocking_Synchronizer3.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/6436/hdl/bfm" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/01b2/hdl/bfm_hbm" +incdir+"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/interfaces" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/PHY_IO_PLL" +incdir+"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/2997/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/bfm" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/4506/hdl" +incdir+"/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_clk_wiz_0/design_1_clk_wiz_0_clk_wiz_top.v" \
  "../../../bd/design_1/ip/design_1_clk_wiz_0/sim/design_1_clk_wiz_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work lib_cdc_v1_0_3 -V93 $xmvhdl_opts \
  "../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/2a4f/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work proc_sys_reset_v5_0_16 -V93 $xmvhdl_opts \
  "../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/0831/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/design_1/ip/design_1_rst_clk_wiz_100M_0/sim/design_1_rst_clk_wiz_100M_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/6436/hdl/bfm" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/01b2/hdl/bfm_hbm" +incdir+"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/interfaces" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/PHY_IO_PLL" +incdir+"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/2997/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/bfm" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" +incdir+"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/4506/hdl" +incdir+"/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
  "../../../bd/design_1/sim/design_1.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts \
  glbl.v \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null
}

# RUN_STEP: <elaborate>
elaborate()
{
  xmelab $xmelab_opts $design_libs_elab xil_defaultlib.design_1 xil_defaultlib.glbl
}

# RUN_STEP: <simulate>
simulate()
{
  xmsim $xmsim_opts xil_defaultlib.design_1 -input simulate.do
}

# STEP: setup
setup()
{
  # delete previous files for a clean rerun
  if [[ ($b_reset_run == 1) ]]; then
    reset_run
    echo -e "INFO: Simulation run files deleted.\n"
    exit 0
  fi

 # delete previous log files
  if [[ ($b_reset_log == 1) ]]; then
    reset_log
    echo -e "INFO: Simulation run log files deleted.\n"
    exit 0
  fi

  # add any setup/initialization commands here:-

  # <user specific commands>

}

# simulator index file/library directory processing
init_lib()
{
  if [[ ($b_keep_index == 1) ]]; then
    # keep previous design library mappings
    true
  else
    # define design library mappings
    create_lib_mappings
  fi

  if [[ ($b_keep_index == 1) ]]; then
    # do not recreate design library directories
    true
  else
    # create design library directories
    create_lib_dir
  fi
}

# define design library mappings
create_lib_mappings()
{
  file="hdl.var"
  touch $file

  file="cds.lib"
  if [[ -e $file ]]; then
    if [[ ($lib_map_path == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  if [[ ($lib_map_path != "") && !(-e $lib_map_path) ]]; then
    echo -e "ERROR: Compiled simulation library directory path not specified or does not exist (type "./top.sh -help" for more information)\n"
  fi

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="INCLUDE $lib_map_path/cds.lib"
    echo $incl_ref >> $file
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="DEFINE $lib $sim_lib_dir/$lib"
    echo $mapping >> $file
  done
}

# create design library directory
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi
  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# delete generated data from the previous run
reset_run()
{
  files_to_remove=(xmvlog.log xmvhdl.log xmsc.log compile.log elaborate.log simulate.log diag_report.log xsc_report.log design_1_sc.so .tmp_log xcelium_lib waves.shm c.obj)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done
}

# delete generated log files from the previous run
reset_log()
{
  files_to_remove=(xmvlog.log xmvhdl.log xmsc.log compile.log elaborate.log simulate.log diag_report.log xsc_report.log .tmp_log)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done
}

# check switch argument value
check_arg_value()
{
  if [[ ($1 == "-step") && (($2 != "compile") && ($2 != "elaborate") && ($2 != "simulate")) ]];then
    echo -e "ERROR: Invalid or missing step '$2' (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($1 == "-lib_map_path") && ($2 == "") ]];then
    echo -e "ERROR: Simulation library directory path not specified (type \"./design_1.sh -help\" for more information)\n"
    exit 1
  fi
}

# check command line arguments
check_args()
{
  arg_count=$#
  if [[ ("$#" == 1) && (("$1" == "-help") || ("$1" == "-h")) ]]; then
    usage
  fi
  while [[ "$#" -gt 0 ]]; do
    case $1 in
      -step)          check_arg_value $1 $2;step=$2;         b_step=1;         shift;;
      -lib_map_path)  check_arg_value $1 $2;lib_map_path=$2; b_lib_map_path=1; shift;;
      -gen_bypass)    b_gen_bypass=1    ;;
      -reset_run)     b_reset_run=1     ;;
      -reset_log)     b_reset_log=1     ;;
      -keep_index)    b_keep_index=1    ;;
      -noclean_files) b_noclean_files=1 ;;
      -help|-h)       ;;
      *) echo -e "ERROR: Invalid option specified '$1' (type "./top.sh -help" for more information)\n"; exit 1 ;;
    esac
     shift
  done

  # -reset_run is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_reset_run == 1) ]]; then
    echo -e "ERROR: -reset_run switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -reset_log is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_reset_log == 1) ]]; then
    echo -e "ERROR: -reset_log switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -keep_index is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_keep_index == 1) ]]; then
    echo -e "ERROR: -keep_index switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -noclean_files is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_noclean_files == 1) ]]; then
    echo -e "ERROR: -noclean_files switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi
}

# script usage
usage()
{
  msg="Usage: design_1.sh [-help]\n\
Usage: design_1.sh [-step]\n\
Usage: design_1.sh [-lib_map_path]\n\
Usage: design_1.sh [-reset_run]\n\
Usage: design_1.sh [-reset_log]\n\
Usage: design_1.sh [-keep_index]\n\
Usage: design_1.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-step <name>] -- Execute specified step (simulate)\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Delete simulator generated data files from the previous run and recreate simulator setup\n\
file/library mappings for a clean run. This switch will not execute steps defined in the script.\n\n\
NOTE: To keep simulator index file settings from the previous run, use the -keep_index switch\n\
NOTE: To regenerate simulator index file but keep the simulator generated files, use the -noclean_files switch\n\n\
[-reset_log] -- Delete simulator generated log files from the previous run\n\n\
[-keep_index] -- Keep simulator index file settings from the previous run\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run\n"
  echo -e $msg
  exit 0
}

# initialize globals
step=""
lib_map_path=""
b_step=0
b_lib_map_path=0
b_gen_bypass=0
b_reset_run=0
b_reset_log=0
b_keep_index=0
b_noclean_files=0

# launch script
run $*
