vlib questa_lib/work
vlib questa_lib/msim

vlib questa_lib/msim/xilinx_vip
vlib questa_lib/msim/xpm
vlib questa_lib/msim/noc_nmu_sim_v1_0_0
vlib questa_lib/msim/noc_hbm_nmu_sim_v1_0_0
vlib questa_lib/msim/xil_defaultlib
vlib questa_lib/msim/xlconstant_v1_1_9
vlib questa_lib/msim/noc_hbm_v1_0_1
vlib questa_lib/msim/clk_gen_sim_v1_0_4
vlib questa_lib/msim/axi_infrastructure_v1_1_0
vlib questa_lib/msim/axi_register_slice_v2_1_33
vlib questa_lib/msim/axis_dbg_stub_v1_0_1
vlib questa_lib/msim/axis_dbg_sync_v1_0_1
vlib questa_lib/msim/axis_vio_v1_0_12
vlib questa_lib/msim/axi_vip_v1_1_19
vlib questa_lib/msim/axis_infrastructure_v1_1_1
vlib questa_lib/msim/axi4stream_vip_v1_1_19
vlib questa_lib/msim/perf_axi_tg_v1_0_15
vlib questa_lib/msim/lib_pkg_v1_0_4
vlib questa_lib/msim/axi_apb_bridge_v3_0_20
vlib questa_lib/msim/sim_trig_v1_0_13
vlib questa_lib/msim/axi_pmon_v1_0_2
vlib questa_lib/msim/lib_cdc_v1_0_3
vlib questa_lib/msim/proc_sys_reset_v5_0_16

vmap xilinx_vip questa_lib/msim/xilinx_vip
vmap xpm questa_lib/msim/xpm
vmap noc_nmu_sim_v1_0_0 questa_lib/msim/noc_nmu_sim_v1_0_0
vmap noc_hbm_nmu_sim_v1_0_0 questa_lib/msim/noc_hbm_nmu_sim_v1_0_0
vmap xil_defaultlib questa_lib/msim/xil_defaultlib
vmap xlconstant_v1_1_9 questa_lib/msim/xlconstant_v1_1_9
vmap noc_hbm_v1_0_1 questa_lib/msim/noc_hbm_v1_0_1
vmap clk_gen_sim_v1_0_4 questa_lib/msim/clk_gen_sim_v1_0_4
vmap axi_infrastructure_v1_1_0 questa_lib/msim/axi_infrastructure_v1_1_0
vmap axi_register_slice_v2_1_33 questa_lib/msim/axi_register_slice_v2_1_33
vmap axis_dbg_stub_v1_0_1 questa_lib/msim/axis_dbg_stub_v1_0_1
vmap axis_dbg_sync_v1_0_1 questa_lib/msim/axis_dbg_sync_v1_0_1
vmap axis_vio_v1_0_12 questa_lib/msim/axis_vio_v1_0_12
vmap axi_vip_v1_1_19 questa_lib/msim/axi_vip_v1_1_19
vmap axis_infrastructure_v1_1_1 questa_lib/msim/axis_infrastructure_v1_1_1
vmap axi4stream_vip_v1_1_19 questa_lib/msim/axi4stream_vip_v1_1_19
vmap perf_axi_tg_v1_0_15 questa_lib/msim/perf_axi_tg_v1_0_15
vmap lib_pkg_v1_0_4 questa_lib/msim/lib_pkg_v1_0_4
vmap axi_apb_bridge_v3_0_20 questa_lib/msim/axi_apb_bridge_v3_0_20
vmap sim_trig_v1_0_13 questa_lib/msim/sim_trig_v1_0_13
vmap axi_pmon_v1_0_2 questa_lib/msim/axi_pmon_v1_0_2
vmap lib_cdc_v1_0_3 questa_lib/msim/lib_cdc_v1_0_3
vmap proc_sys_reset_v5_0_16 questa_lib/msim/proc_sys_reset_v5_0_16

vlog -work xilinx_vip -64 -incr -mfcu  -sv -L clk_gen_sim_v1_0_4 -L sim_trig_v1_0_13 -L axi4stream_vip_v1_1_19 -L axi_vip_v1_1_19 -L perf_axi_tg_v1_0_15 -L axi_pmon_v1_0_2 -L noc_nps4_v1_0_0 -L noc_nps6_v1_0_0 -L axis_vio_v1_0_12 -L noc_hbm_nmu_sim_v1_0_0 -L noc_nmu_sim_v1_0_0 -L noc_hbm_v1_0_1 -L xilinx_vip "+incdir+/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
"/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
"/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
"/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
"/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
"/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
"/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
"/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
"/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/hdl/rst_vip_if.sv" \

vlog -work xpm -64 -incr -mfcu  -sv -L clk_gen_sim_v1_0_4 -L sim_trig_v1_0_13 -L axi4stream_vip_v1_1_19 -L axi_vip_v1_1_19 -L perf_axi_tg_v1_0_15 -L axi_pmon_v1_0_2 -L noc_nps4_v1_0_0 -L noc_nps6_v1_0_0 -L axis_vio_v1_0_12 -L noc_hbm_nmu_sim_v1_0_0 -L noc_nmu_sim_v1_0_0 -L noc_hbm_v1_0_1 -L xilinx_vip "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/6436/hdl/bfm" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/01b2/hdl/bfm_hbm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/interfaces" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/PHY_IO_PLL" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/2997/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/434f/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/bfm" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/4506/hdl" "+incdir+/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"/tools/Xilinx/Vivado/2024.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
"/tools/Xilinx/Vivado/2024.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
"/tools/Xilinx/Vivado/2024.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \

vcom -work xpm -64 -93  \
"/tools/Xilinx/Vivado/2024.2/data/ip/xpm/xpm_VCOMP.vhd" \

vlog -work noc_nmu_sim_v1_0_0 -64 -incr -mfcu  -sv -L clk_gen_sim_v1_0_4 -L sim_trig_v1_0_13 -L axi4stream_vip_v1_1_19 -L axi_vip_v1_1_19 -L perf_axi_tg_v1_0_15 -L axi_pmon_v1_0_2 -L noc_nps4_v1_0_0 -L noc_nps6_v1_0_0 -L axis_vio_v1_0_12 -L noc_hbm_nmu_sim_v1_0_0 -L noc_nmu_sim_v1_0_0 -L noc_hbm_v1_0_1 -L xilinx_vip "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/6436/hdl/bfm" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/01b2/hdl/bfm_hbm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/interfaces" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/PHY_IO_PLL" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/2997/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/434f/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/bfm" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/4506/hdl" "+incdir+/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/6436/hdl/noc_nmu_sim_v1_0_vl_rfs.sv" \

vlog -work noc_hbm_nmu_sim_v1_0_0 -64 -incr -mfcu  -sv -L clk_gen_sim_v1_0_4 -L sim_trig_v1_0_13 -L axi4stream_vip_v1_1_19 -L axi_vip_v1_1_19 -L perf_axi_tg_v1_0_15 -L axi_pmon_v1_0_2 -L noc_nps4_v1_0_0 -L noc_nps6_v1_0_0 -L axis_vio_v1_0_12 -L noc_hbm_nmu_sim_v1_0_0 -L noc_nmu_sim_v1_0_0 -L noc_hbm_v1_0_1 -L xilinx_vip "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/6436/hdl/bfm" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/01b2/hdl/bfm_hbm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/interfaces" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/PHY_IO_PLL" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/2997/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/434f/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/bfm" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/4506/hdl" "+incdir+/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/01b2/hdl/noc_hbm_nmu_sim_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib -64 -incr -mfcu  -sv -L clk_gen_sim_v1_0_4 -L sim_trig_v1_0_13 -L axi4stream_vip_v1_1_19 -L axi_vip_v1_1_19 -L perf_axi_tg_v1_0_15 -L axi_pmon_v1_0_2 -L noc_nps4_v1_0_0 -L noc_nps6_v1_0_0 -L axis_vio_v1_0_12 -L noc_hbm_nmu_sim_v1_0_0 -L noc_nmu_sim_v1_0_0 -L noc_hbm_v1_0_1 -L xilinx_vip "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/6436/hdl/bfm" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/01b2/hdl/bfm_hbm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/interfaces" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/PHY_IO_PLL" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/2997/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/434f/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/bfm" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/4506/hdl" "+incdir+/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_0/hdl/bfm/bd_8be5_HBM00_AXI_nmu_0_top.sv" \
"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_0/hdl/bfm/bd_8be5_HBM00_AXI_nmu_0.sv" \

vlog -work xlconstant_v1_1_9 -64 -incr -mfcu  "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/6436/hdl/bfm" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/01b2/hdl/bfm_hbm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/interfaces" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/PHY_IO_PLL" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/2997/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/434f/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/bfm" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/4506/hdl" "+incdir+/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/e2d2/hdl/xlconstant_v1_1_vl_rfs.v" \

vlog -work xil_defaultlib -64 -incr -mfcu  "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/6436/hdl/bfm" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/01b2/hdl/bfm_hbm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/interfaces" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/PHY_IO_PLL" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/2997/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/434f/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/bfm" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/4506/hdl" "+incdir+/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_1/sim/bd_8be5_const_0_0.v" \

vlog -work xil_defaultlib -64 -incr -mfcu  -sv -L clk_gen_sim_v1_0_4 -L sim_trig_v1_0_13 -L axi4stream_vip_v1_1_19 -L axi_vip_v1_1_19 -L perf_axi_tg_v1_0_15 -L axi_pmon_v1_0_2 -L noc_nps4_v1_0_0 -L noc_nps6_v1_0_0 -L axis_vio_v1_0_12 -L noc_hbm_nmu_sim_v1_0_0 -L noc_nmu_sim_v1_0_0 -L noc_hbm_v1_0_1 -L xilinx_vip "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/6436/hdl/bfm" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/01b2/hdl/bfm_hbm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/interfaces" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/PHY_IO_PLL" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/2997/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/434f/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/bfm" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/4506/hdl" "+incdir+/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/rtl/bd_8be5_MC_hbmc_0_top_unisim_stack0.sv" \
"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/rtl/bd_8be5_MC_hbmc_0_top_wrapper.sv" \

vlog -work noc_hbm_v1_0_1 -64 -incr -mfcu  -sv -L clk_gen_sim_v1_0_4 -L sim_trig_v1_0_13 -L axi4stream_vip_v1_1_19 -L axi_vip_v1_1_19 -L perf_axi_tg_v1_0_15 -L axi_pmon_v1_0_2 -L noc_nps4_v1_0_0 -L noc_nps6_v1_0_0 -L axis_vio_v1_0_12 -L noc_hbm_nmu_sim_v1_0_0 -L noc_nmu_sim_v1_0_0 -L noc_hbm_v1_0_1 -L xilinx_vip "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/6436/hdl/bfm" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/01b2/hdl/bfm_hbm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/interfaces" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/PHY_IO_PLL" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/2997/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/434f/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/bfm" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/4506/hdl" "+incdir+/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/Unisims/HBM_CHNL.sv" \
"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/Unisims/HBM_CHNL_PHY_ONLY.sv" \
"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/BM_HBM_MC.sv" \
"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/hbm_dbuf_bfm.sv" \
"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/hbm_dc_bfm.sv" \
"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/hbm_dpath_bfm.sv" \
"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/hbm_refresh_bfm.sv" \
"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/hbm_txnq_bfm.sv" \
"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/hbm_pend_fifo_bfm.sv" \
"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/hbm_farb_bfm.sv" \
"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/hbmmc_na_bfm.sv" \
"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/lbus_checker.sv" \
"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/hbmmc_mc_bfm.sv" \
"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/hbm_ctrl_bfm.sv" \
"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/hbm_bfm_phy_shim.sv" \
"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/PHY_IO_PLL/BM_HBM_IO_CHNL.sv" \
"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/PHY_IO_PLL/BM_HBM_PHY_CHNL.sv" \
"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/PHY_IO_PLL/BM_HPLL.sv" \
"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/PHY_IO_PLL/cmt_hbm_hpll_bfm.sv" \
"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/PHY_IO_PLL/hbm_io_chnl_top_bfm.sv" \
"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/PHY_IO_PLL/hbm_phy_chnl_8_1_bfm.sv" \
"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/PHY_IO_PLL/hbm_phy_chnl_intf_bfm.sv" \
"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/PHY_IO_PLL/hbm_phy_chnl_top_bfm.sv" \

vlog -work xil_defaultlib -64 -incr -mfcu  -sv -L clk_gen_sim_v1_0_4 -L sim_trig_v1_0_13 -L axi4stream_vip_v1_1_19 -L axi_vip_v1_1_19 -L perf_axi_tg_v1_0_15 -L axi_pmon_v1_0_2 -L noc_nps4_v1_0_0 -L noc_nps6_v1_0_0 -L axis_vio_v1_0_12 -L noc_hbm_nmu_sim_v1_0_0 -L noc_nmu_sim_v1_0_0 -L noc_hbm_v1_0_1 -L xilinx_vip "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/6436/hdl/bfm" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/01b2/hdl/bfm_hbm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/interfaces" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/PHY_IO_PLL" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/2997/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/434f/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/bfm" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/4506/hdl" "+incdir+/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model/hbm_responder.sv" \
"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/bfm/PHY_IO_PLL/BM_HBM_PHY_MS.sv" \
"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/bfm/PHY_IO_PLL/BM_IO_MS.sv" \
"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/bfm/PHY_IO_PLL/hbm_io_ms_top_bfm.sv" \
"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/bfm/PHY_IO_PLL/hbm_phy_ms_top_bfm.sv" \
"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/rtl/bd_8be5_MC_hbmc_0.sv" \

vlog -work xil_defaultlib -64 -incr -mfcu  "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/6436/hdl/bfm" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/01b2/hdl/bfm_hbm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/interfaces" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/PHY_IO_PLL" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/2997/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/434f/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/bfm" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/4506/hdl" "+incdir+/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/sim/bd_8be5.v" \
"../../../bd/design_1/ip/design_1_axi_noc_0_0/sim/design_1_axi_noc_0_0.v" \

vlog -work clk_gen_sim_v1_0_4 -64 -incr -mfcu  -sv -L clk_gen_sim_v1_0_4 -L sim_trig_v1_0_13 -L axi4stream_vip_v1_1_19 -L axi_vip_v1_1_19 -L perf_axi_tg_v1_0_15 -L axi_pmon_v1_0_2 -L noc_nps4_v1_0_0 -L noc_nps6_v1_0_0 -L axis_vio_v1_0_12 -L noc_hbm_nmu_sim_v1_0_0 -L noc_nmu_sim_v1_0_0 -L noc_hbm_v1_0_1 -L xilinx_vip "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/6436/hdl/bfm" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/01b2/hdl/bfm_hbm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/interfaces" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/PHY_IO_PLL" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/2997/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/434f/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/bfm" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/4506/hdl" "+incdir+/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/0c0c/hdl/clk_gen_sim_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib -64 -incr -mfcu  -sv -L clk_gen_sim_v1_0_4 -L sim_trig_v1_0_13 -L axi4stream_vip_v1_1_19 -L axi_vip_v1_1_19 -L perf_axi_tg_v1_0_15 -L axi_pmon_v1_0_2 -L noc_nps4_v1_0_0 -L noc_nps6_v1_0_0 -L axis_vio_v1_0_12 -L noc_hbm_nmu_sim_v1_0_0 -L noc_nmu_sim_v1_0_0 -L noc_hbm_v1_0_1 -L xilinx_vip "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/6436/hdl/bfm" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/01b2/hdl/bfm_hbm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/interfaces" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/PHY_IO_PLL" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/2997/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/434f/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/bfm" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/4506/hdl" "+incdir+/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_noc_clk_gen_0/hdl/design_1_noc_clk_gen_0.sv" \

vlog -work axi_infrastructure_v1_1_0 -64 -incr -mfcu  "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/6436/hdl/bfm" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/01b2/hdl/bfm_hbm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/interfaces" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/PHY_IO_PLL" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/2997/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/434f/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/bfm" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/4506/hdl" "+incdir+/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \

vlog -work axi_register_slice_v2_1_33 -64 -incr -mfcu  "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/6436/hdl/bfm" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/01b2/hdl/bfm_hbm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/interfaces" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/PHY_IO_PLL" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/2997/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/434f/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/bfm" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/4506/hdl" "+incdir+/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/3ee4/hdl/axi_register_slice_v2_1_vl_rfs.v" \

vlog -work xil_defaultlib -64 -incr -mfcu  "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/6436/hdl/bfm" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/01b2/hdl/bfm_hbm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/interfaces" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/PHY_IO_PLL" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/2997/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/434f/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/bfm" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/4506/hdl" "+incdir+/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_noc_tg_0/ip_0/sim/design_1_noc_tg_0_axi4_register_slice.v" \
"../../../bd/design_1/ip/design_1_noc_tg_0/ip_1/sim/design_1_noc_tg_0_axi_register_slice_wronly.v" \

vlog -work axis_dbg_stub_v1_0_1 -64 -incr -mfcu  "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/6436/hdl/bfm" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/01b2/hdl/bfm_hbm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/interfaces" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/PHY_IO_PLL" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/2997/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/434f/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/bfm" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/4506/hdl" "+incdir+/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b54f/hdl/axis_dbg_stub_v1_0_rfs.v" \

vlog -work axis_dbg_sync_v1_0_1 -64 -incr -mfcu  "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/6436/hdl/bfm" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/01b2/hdl/bfm_hbm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/interfaces" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/PHY_IO_PLL" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/2997/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/434f/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/bfm" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/4506/hdl" "+incdir+/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/7899/hdl/axis_dbg_sync_v1_0_vl_rfs.v" \

vlog -work axis_vio_v1_0_12 -64 -incr -mfcu  -sv -L clk_gen_sim_v1_0_4 -L sim_trig_v1_0_13 -L axi4stream_vip_v1_1_19 -L axi_vip_v1_1_19 -L perf_axi_tg_v1_0_15 -L axi_pmon_v1_0_2 -L noc_nps4_v1_0_0 -L noc_nps6_v1_0_0 -L axis_vio_v1_0_12 -L noc_hbm_nmu_sim_v1_0_0 -L noc_nmu_sim_v1_0_0 -L noc_hbm_v1_0_1 -L xilinx_vip "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/6436/hdl/bfm" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/01b2/hdl/bfm_hbm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/interfaces" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/PHY_IO_PLL" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/2997/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/434f/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/bfm" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/4506/hdl" "+incdir+/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/2997/hdl/axis_vio_v1_0_rfs.sv" \

vlog -work xil_defaultlib -64 -incr -mfcu  "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/6436/hdl/bfm" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/01b2/hdl/bfm_hbm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/interfaces" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/PHY_IO_PLL" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/2997/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/434f/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/bfm" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/4506/hdl" "+incdir+/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_noc_tg_0/ip_2/sim/design_1_noc_tg_0_vio.v" \

vlog -work xil_defaultlib -64 -incr -mfcu  -sv -L clk_gen_sim_v1_0_4 -L sim_trig_v1_0_13 -L axi4stream_vip_v1_1_19 -L axi_vip_v1_1_19 -L perf_axi_tg_v1_0_15 -L axi_pmon_v1_0_2 -L noc_nps4_v1_0_0 -L noc_nps6_v1_0_0 -L axis_vio_v1_0_12 -L noc_hbm_nmu_sim_v1_0_0 -L noc_nmu_sim_v1_0_0 -L noc_hbm_v1_0_1 -L xilinx_vip "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/6436/hdl/bfm" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/01b2/hdl/bfm_hbm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/interfaces" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/PHY_IO_PLL" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/2997/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/434f/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/bfm" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/4506/hdl" "+incdir+/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_noc_tg_0/ip_3/sim/design_1_noc_tg_0_vip_pkg.sv" \

vlog -work axi_vip_v1_1_19 -64 -incr -mfcu  -sv -L clk_gen_sim_v1_0_4 -L sim_trig_v1_0_13 -L axi4stream_vip_v1_1_19 -L axi_vip_v1_1_19 -L perf_axi_tg_v1_0_15 -L axi_pmon_v1_0_2 -L noc_nps4_v1_0_0 -L noc_nps6_v1_0_0 -L axis_vio_v1_0_12 -L noc_hbm_nmu_sim_v1_0_0 -L noc_nmu_sim_v1_0_0 -L noc_hbm_v1_0_1 -L xilinx_vip "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/6436/hdl/bfm" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/01b2/hdl/bfm_hbm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/interfaces" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/PHY_IO_PLL" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/2997/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/434f/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/bfm" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/4506/hdl" "+incdir+/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/8c45/hdl/axi_vip_v1_1_vl_rfs.sv" \

vlog -work xil_defaultlib -64 -incr -mfcu  -sv -L clk_gen_sim_v1_0_4 -L sim_trig_v1_0_13 -L axi4stream_vip_v1_1_19 -L axi_vip_v1_1_19 -L perf_axi_tg_v1_0_15 -L axi_pmon_v1_0_2 -L noc_nps4_v1_0_0 -L noc_nps6_v1_0_0 -L axis_vio_v1_0_12 -L noc_hbm_nmu_sim_v1_0_0 -L noc_nmu_sim_v1_0_0 -L noc_hbm_v1_0_1 -L xilinx_vip "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/6436/hdl/bfm" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/01b2/hdl/bfm_hbm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/interfaces" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/PHY_IO_PLL" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/2997/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/434f/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/bfm" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/4506/hdl" "+incdir+/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_noc_tg_0/ip_3/sim/design_1_noc_tg_0_vip.sv" \

vlog -work axis_infrastructure_v1_1_1 -64 -incr -mfcu  "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/6436/hdl/bfm" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/01b2/hdl/bfm_hbm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/interfaces" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/PHY_IO_PLL" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/2997/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/434f/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/bfm" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/4506/hdl" "+incdir+/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/434f/hdl/axis_infrastructure_v1_1_vl_rfs.v" \

vlog -work axi4stream_vip_v1_1_19 -64 -incr -mfcu  -sv -L clk_gen_sim_v1_0_4 -L sim_trig_v1_0_13 -L axi4stream_vip_v1_1_19 -L axi_vip_v1_1_19 -L perf_axi_tg_v1_0_15 -L axi_pmon_v1_0_2 -L noc_nps4_v1_0_0 -L noc_nps6_v1_0_0 -L axis_vio_v1_0_12 -L noc_hbm_nmu_sim_v1_0_0 -L noc_nmu_sim_v1_0_0 -L noc_hbm_v1_0_1 -L xilinx_vip "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/6436/hdl/bfm" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/01b2/hdl/bfm_hbm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/interfaces" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/PHY_IO_PLL" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/2997/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/434f/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/bfm" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/4506/hdl" "+incdir+/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/51ff/hdl/axi4stream_vip_v1_1_vl_rfs.sv" \

vlog -work perf_axi_tg_v1_0_15 -64 -incr -mfcu  -sv -L clk_gen_sim_v1_0_4 -L sim_trig_v1_0_13 -L axi4stream_vip_v1_1_19 -L axi_vip_v1_1_19 -L perf_axi_tg_v1_0_15 -L axi_pmon_v1_0_2 -L noc_nps4_v1_0_0 -L noc_nps6_v1_0_0 -L axis_vio_v1_0_12 -L noc_hbm_nmu_sim_v1_0_0 -L noc_nmu_sim_v1_0_0 -L noc_hbm_v1_0_1 -L xilinx_vip "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/6436/hdl/bfm" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/01b2/hdl/bfm_hbm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/interfaces" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/PHY_IO_PLL" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/2997/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/434f/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/bfm" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/4506/hdl" "+incdir+/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/bfm/axi_data_integrity_checker.sv" \
"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/bfm/addr_cls_pkg.sv" \
"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/bfm/top_axi_mst_ext_if.sv" \
"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/bfm/top_axis_mst_ext_if.sv" \

vlog -work xil_defaultlib -64 -incr -mfcu  -sv -L clk_gen_sim_v1_0_4 -L sim_trig_v1_0_13 -L axi4stream_vip_v1_1_19 -L axi_vip_v1_1_19 -L perf_axi_tg_v1_0_15 -L axi_pmon_v1_0_2 -L noc_nps4_v1_0_0 -L noc_nps6_v1_0_0 -L axis_vio_v1_0_12 -L noc_hbm_nmu_sim_v1_0_0 -L noc_nmu_sim_v1_0_0 -L noc_hbm_v1_0_1 -L xilinx_vip "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/6436/hdl/bfm" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/01b2/hdl/bfm_hbm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/interfaces" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/PHY_IO_PLL" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/2997/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/434f/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/bfm" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/4506/hdl" "+incdir+/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_noc_tg_0/hdl/rtl/design_1_noc_tg_0_tg_top.sv" \
"../../../bd/design_1/ip/design_1_noc_tg_0/hdl/rtl/design_1_noc_tg_0_csvsptg_top.sv" \
"../../../bd/design_1/ip/design_1_noc_tg_0/hdl/bfm/design_1_noc_tg_0_top.sv" \
"../../../bd/design_1/ip/design_1_noc_tg_0/hdl/csv_sptg/rtl/tg_rtl/design_1_noc_tg_0_syn_top.sv" \
"../../../bd/design_1/ip/design_1_noc_tg_0/hdl/bfm/design_1_noc_tg_0_top_axi_mst.sv" \
"../../../bd/design_1/ip/design_1_noc_tg_0/hdl/rtl/design_1_noc_tg_0_reg_space.sv" \
"../../../bd/design_1/ip/design_1_noc_tg_0/hdl/rtl/design_1_noc_tg_0_top_axi_stream_sptg.sv" \

vlog -work perf_axi_tg_v1_0_15 -64 -incr -mfcu  -sv -L clk_gen_sim_v1_0_4 -L sim_trig_v1_0_13 -L axi4stream_vip_v1_1_19 -L axi_vip_v1_1_19 -L perf_axi_tg_v1_0_15 -L axi_pmon_v1_0_2 -L noc_nps4_v1_0_0 -L noc_nps6_v1_0_0 -L axis_vio_v1_0_12 -L noc_hbm_nmu_sim_v1_0_0 -L noc_nmu_sim_v1_0_0 -L noc_hbm_v1_0_1 -L xilinx_vip "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/6436/hdl/bfm" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/01b2/hdl/bfm_hbm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/interfaces" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/PHY_IO_PLL" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/2997/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/434f/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/bfm" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/4506/hdl" "+incdir+/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl/axi_inst_core.sv" \
"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl/axi_rdch_ctrl.sv" \
"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl/axi_stream_inst_core.sv" \
"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl/axi_stream_sptg.sv" \
"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl/axi_wrch_ctrl.sv" \
"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl/mem_tg_mode_data_pat_generator.sv" \
"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl/axi_rd_wr_err_detect.sv" \
"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl/atg_axi_tg_data_prbs.sv" \
"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl/atg_axi_tg_prbs_gen.sv" \
"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl/atg_axi_tg_data_prbs_seed.sv" \
"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl/cfg_reg_rw.sv" \
"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl/cnst_id_latency.sv" \
"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl/di_check_cnst_id.sv" \
"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl/di_check_mult_id.sv" \
"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl/incr_id_latency.sv" \
"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl/inst_fetch.sv" \
"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl/inst_fifo.sv" \
"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl/addr_decoder.sv" \
"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl/prbs_data_gen.sv" \
"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl/prbs_generator_32b.sv" \
"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl/reg_space_stream.sv" \
"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl/mem_strobe_gen.sv" \
"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl/mem_strb_stream_gen.sv" \
"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl/trig_in_out_sync.sv" \
"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl/sptg_synchronizer.sv" \

vlog -work xil_defaultlib -64 -incr -mfcu  -sv -L clk_gen_sim_v1_0_4 -L sim_trig_v1_0_13 -L axi4stream_vip_v1_1_19 -L axi_vip_v1_1_19 -L perf_axi_tg_v1_0_15 -L axi_pmon_v1_0_2 -L noc_nps4_v1_0_0 -L noc_nps6_v1_0_0 -L axis_vio_v1_0_12 -L noc_hbm_nmu_sim_v1_0_0 -L noc_nmu_sim_v1_0_0 -L noc_hbm_v1_0_1 -L xilinx_vip "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/6436/hdl/bfm" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/01b2/hdl/bfm_hbm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/interfaces" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/PHY_IO_PLL" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/2997/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/434f/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/bfm" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/4506/hdl" "+incdir+/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_noc_tg_0/sim/design_1_noc_tg_0.sv" \

vcom -work lib_pkg_v1_0_4 -64 -93  \
"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/8c68/hdl/lib_pkg_v1_0_rfs.vhd" \

vcom -work axi_apb_bridge_v3_0_20 -64 -93  \
"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/8d5f/hdl/axi_apb_bridge_v3_0_vh_rfs.vhd" \

vcom -work xil_defaultlib -64 -93  \
"../../../bd/design_1/ip/design_1_noc_sim_trig_0/ip_0/sim/axi_apb_bridge_0.vhd" \

vlog -work xil_defaultlib -64 -incr -mfcu  -sv -L clk_gen_sim_v1_0_4 -L sim_trig_v1_0_13 -L axi4stream_vip_v1_1_19 -L axi_vip_v1_1_19 -L perf_axi_tg_v1_0_15 -L axi_pmon_v1_0_2 -L noc_nps4_v1_0_0 -L noc_nps6_v1_0_0 -L axis_vio_v1_0_12 -L noc_hbm_nmu_sim_v1_0_0 -L noc_nmu_sim_v1_0_0 -L noc_hbm_v1_0_1 -L xilinx_vip "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/6436/hdl/bfm" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/01b2/hdl/bfm_hbm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/interfaces" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/PHY_IO_PLL" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/2997/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/434f/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/bfm" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/4506/hdl" "+incdir+/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_noc_sim_trig_0/hdl/design_1_noc_sim_trig_0_top.sv" \
"../../../bd/design_1/ip/design_1_noc_sim_trig_0/hdl/design_1_noc_sim_trig_0.sv" \

vlog -work sim_trig_v1_0_13 -64 -incr -mfcu  -sv -L clk_gen_sim_v1_0_4 -L sim_trig_v1_0_13 -L axi4stream_vip_v1_1_19 -L axi_vip_v1_1_19 -L perf_axi_tg_v1_0_15 -L axi_pmon_v1_0_2 -L noc_nps4_v1_0_0 -L noc_nps6_v1_0_0 -L axis_vio_v1_0_12 -L noc_hbm_nmu_sim_v1_0_0 -L noc_nmu_sim_v1_0_0 -L noc_hbm_v1_0_1 -L xilinx_vip "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/6436/hdl/bfm" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/01b2/hdl/bfm_hbm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/interfaces" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/PHY_IO_PLL" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/2997/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/434f/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/bfm" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/4506/hdl" "+incdir+/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/9cb8/hdl/sim_trig_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib -64 -incr -mfcu  -sv -L clk_gen_sim_v1_0_4 -L sim_trig_v1_0_13 -L axi4stream_vip_v1_1_19 -L axi_vip_v1_1_19 -L perf_axi_tg_v1_0_15 -L axi_pmon_v1_0_2 -L noc_nps4_v1_0_0 -L noc_nps6_v1_0_0 -L axis_vio_v1_0_12 -L noc_hbm_nmu_sim_v1_0_0 -L noc_nmu_sim_v1_0_0 -L noc_hbm_v1_0_1 -L xilinx_vip "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/6436/hdl/bfm" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/01b2/hdl/bfm_hbm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/interfaces" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/PHY_IO_PLL" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/2997/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/434f/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/bfm" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/4506/hdl" "+incdir+/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_noc_sim_trig_0/hdl/rtl/traffic_shaping.sv" \

vlog -work axi_pmon_v1_0_2 -64 -incr -mfcu  -sv -L clk_gen_sim_v1_0_4 -L sim_trig_v1_0_13 -L axi4stream_vip_v1_1_19 -L axi_vip_v1_1_19 -L perf_axi_tg_v1_0_15 -L axi_pmon_v1_0_2 -L noc_nps4_v1_0_0 -L noc_nps6_v1_0_0 -L axis_vio_v1_0_12 -L noc_hbm_nmu_sim_v1_0_0 -L noc_nmu_sim_v1_0_0 -L noc_hbm_v1_0_1 -L xilinx_vip "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/6436/hdl/bfm" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/01b2/hdl/bfm_hbm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/interfaces" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/PHY_IO_PLL" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/2997/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/434f/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/bfm" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/4506/hdl" "+incdir+/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/3f57/hdl/axi_pmon_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib -64 -incr -mfcu  -sv -L clk_gen_sim_v1_0_4 -L sim_trig_v1_0_13 -L axi4stream_vip_v1_1_19 -L axi_vip_v1_1_19 -L perf_axi_tg_v1_0_15 -L axi_pmon_v1_0_2 -L noc_nps4_v1_0_0 -L noc_nps6_v1_0_0 -L axis_vio_v1_0_12 -L noc_hbm_nmu_sim_v1_0_0 -L noc_nmu_sim_v1_0_0 -L noc_hbm_v1_0_1 -L xilinx_vip "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/6436/hdl/bfm" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/01b2/hdl/bfm_hbm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/interfaces" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/PHY_IO_PLL" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/2997/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/434f/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/bfm" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/4506/hdl" "+incdir+/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_noc_tg_pmon_0/sim/design_1_noc_tg_pmon_0.sv" \

vlog -work xil_defaultlib -64 -incr -mfcu  "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/6436/hdl/bfm" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/01b2/hdl/bfm_hbm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/interfaces" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/PHY_IO_PLL" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/2997/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/434f/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/bfm" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/4506/hdl" "+incdir+/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_clk_wiz_0/design_1_clk_wiz_0_clocking_structure.v" \
"../../../bd/design_1/ip/design_1_clk_wiz_0/design_1_clk_wiz_0_clocking_MBUFGCE_CE_DLY.v" \

vlog -work xil_defaultlib -64 -incr -mfcu  -sv -L clk_gen_sim_v1_0_4 -L sim_trig_v1_0_13 -L axi4stream_vip_v1_1_19 -L axi_vip_v1_1_19 -L perf_axi_tg_v1_0_15 -L axi_pmon_v1_0_2 -L noc_nps4_v1_0_0 -L noc_nps6_v1_0_0 -L axis_vio_v1_0_12 -L noc_hbm_nmu_sim_v1_0_0 -L noc_nmu_sim_v1_0_0 -L noc_hbm_v1_0_1 -L xilinx_vip "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/6436/hdl/bfm" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/01b2/hdl/bfm_hbm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/interfaces" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/PHY_IO_PLL" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/2997/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/434f/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/bfm" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/4506/hdl" "+incdir+/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_clk_wiz_0/design_1_clk_wiz_0_clocking_cmt_dpll_fd_cal.sv" \
"../../../bd/design_1/ip/design_1_clk_wiz_0/design_1_clk_wiz_0_clocking_Synchronizer3.sv" \

vlog -work xil_defaultlib -64 -incr -mfcu  "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/6436/hdl/bfm" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/01b2/hdl/bfm_hbm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/interfaces" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/PHY_IO_PLL" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/2997/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/434f/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/bfm" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/4506/hdl" "+incdir+/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_clk_wiz_0/design_1_clk_wiz_0_clk_wiz_top.v" \
"../../../bd/design_1/ip/design_1_clk_wiz_0/sim/design_1_clk_wiz_0.v" \

vcom -work lib_cdc_v1_0_3 -64 -93  \
"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/2a4f/hdl/lib_cdc_v1_0_rfs.vhd" \

vcom -work proc_sys_reset_v5_0_16 -64 -93  \
"../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/0831/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \

vcom -work xil_defaultlib -64 -93  \
"../../../bd/design_1/ip/design_1_rst_clk_wiz_100M_0/sim/design_1_rst_clk_wiz_100M_0.vhd" \

vlog -work xil_defaultlib -64 -incr -mfcu  "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/6436/hdl/bfm" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/01b2/hdl/bfm_hbm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/MC/interfaces" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/b994/hdl/bfm/PHY_IO_PLL" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/2997/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/434f/hdl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/bfm" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/5ace/hdl/rtl" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_0/bd_0/ip/ip_2/hdl/memory_model" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" "+incdir+../../../../hbm_module_1.gen/sources_1/bd/design_1/ipshared/4506/hdl" "+incdir+/tools/Xilinx/Vivado/2024.2/data/xilinx_vip/include" \
"../../../bd/design_1/sim/design_1.v" \

vlog -work xil_defaultlib \
"glbl.v"

